---
title: "2020_05_29 LP preparations"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/n/janson_lab/lab/sma/sparsedossa_update/")
knitr::opts_chunk$set(echo=FALSE)
library(magrittr)
library(ggplot2)
```

```{r setup2, include=FALSE}
# Registry
# batchtools::makeRegistry(file.dir = "r_batchtools_reg/Methods_evaluation",
#                          package = "magrittr")
batchtools::loadRegistry(file.dir = "r_batchtools_reg/Methods_evaluation", 
                         writeable = TRUE)
batchtools::clearRegistry()

# Grid parameters
ncpus <- 45
partition <- "janson_cascade"
walltime <- 48 * 3600

# Output dir
dir_output <- "/n/janson_lab/lab/sma/sparsedossa_update/results/tmp/2020_05_29_LP_preparations/"
dir.create(dir_output, recursive = TRUE, showWarnings = FALSE)
smar::sourceDir("SparseDOSSA2/R/")
```

```{r load datasets}
load("data/physeqs/HMP1II_vaginal.RData")
load("data/physeqs/HMP1II_stool.RData")

x_samples_vaginal <- physeq_vaginal %>% 
  smar::otu_table2() %>% 
  t()
x_samples_vaginal <- 
  x_samples_vaginal[, (x_samples_vaginal > 0) %>% 
                      apply(2, sum) %>% 
                      {. >= 5}]
x_samples_vaginal_count <- x_samples_vaginal
# set to relative abundance
x_samples_vaginal <- 
  x_samples_vaginal %>% 
  apply(1, TSS) %>% 
  t()

x_samples_stool <- physeq_stool %>% 
  smar::otu_table2() %>% 
  t()
x_samples_stool <- 
  x_samples_stool[, (x_samples_stool > 0) %>% 
                      apply(2, sum) %>% 
                      {. >= 5}]
x_samples_stool_count <- x_samples_stool
x_samples_stool <- 
  x_samples_stool %>% 
  apply(1, TSS) %>% 
  t()
```


```{r compare SparseDOSSA fit vs original}
load("results/attic/Stool_vaginal/2020_03_12/fit_3.RData")
fit_vaginal <- fit_EM
load("results/attic/Stool_vaginal/2020_03_12/fit_4.RData")
fit_stool <- fit_EM

set.seed(1)
c("Vaginal", "Stool") %>% 
  purrr::map2(
    c(1, 2),
    function(i_name, i) {
      data <- list(x_samples_vaginal, x_samples_stool)[[i]]
      fit_spd <- list(fit_vaginal, fit_stool)[[i]]
      a_samples <- simulate_a(n = 2000,
                              params = fit_spd$l_fits_full[[1]]$fit)
      a_samples <- a_samples[!apply(a_samples == 0, 1, all), ][seq_len(1000), ]
      x_samples <- apply(a_samples, 1, TSS) %>% t()
      data_combined <- rbind(data, x_samples)
      dist_combined <- vegan::vegdist(data_combined,
                                      method = "bray")
      fit_pcoa <- ape::pcoa(dist_combined)
      tb_plot <- 
        fit_pcoa$vectors %>% 
        tibble::as_tibble() %>% 
        dplyr::mutate(class =
                        c(rep("Original", nrow(data)),
                          rep("SparseDOSSA", 1000)) %>% 
                        forcats::as_factor())
      fit_pnova <- vegan::adonis(dist_combined ~ class,
                                 data = tb_plot,
                                 permutations = 2)
      p <- tb_plot %>% 
        dplyr::arrange(-as.numeric(class)) %>% 
        ggplot(aes(x = Axis.1, y = Axis.2, color = class)) +
        geom_point() +
        theme_bw() +
        coord_fixed() +
        xlab(paste0("PCo1 (", round(fit_pcoa$values[1, 2] * 100, 2), "%)")) +
        ylab(paste0("PCo2 (", round(fit_pcoa$values[2, 2] * 100, 2), "%)")) +
        ggtitle(paste0(i_name, "\n",
                       "R2 = ", round(fit_pnova$aov.tab[1, 5] * 100, 2), "%"))
      ggsave(paste0(dir_output, "ord_", i_name, ".pdf"),
             p,
             width = 6, height = 6)
    })
```

```{r compare mvn fit vs original}
fit_vaginal_mvn <- mvn(data = x_samples_vaginal, lambdas = 1e-4)
save(fit_vaginal_mvn, file = paste0(dir_output, "fit_vaginal_mvn.RData"))
fit_stool_mvn <- mvn(data = x_samples_stool, lambdas = 1e-4)
save(fit_stool_mvn, file = paste0(dir_output, "fit_stool_mvn.RData"))
set.seed(1)
c("vaginal", "stool") %>% 
  purrr::map2(
    c(1, 2),
    function(i_name, i) {
      data <- list(x_samples_vaginal, x_samples_stool)[[i]]
      fit_model <- list(fit_vaginal_mvn, fit_stool_mvn)[[i]]
      a_samples <- 
        mvtnorm::rmvnorm(
          n = 1000,
          mean = fit_model$l_fits[[1]]$fit$mu,
          sigma = 
            diag(sqrt(fit_model$l_fits[[1]]$fit$sigma)) %*%
            fit_model$l_fits[[1]]$fit$Sigma %*%
            diag(sqrt(fit_model$l_fits[[1]]$fit$sigma))
        )
      a_samples <- exp(a_samples) / (1 + exp(a_samples))
      a_samples <- a_samples[!apply(a_samples == 0, 1, all), ][seq_len(1000), ]
      x_samples <- apply(a_samples, 1, TSS) %>% t()
      data_combined <- rbind(data, x_samples)
      dist_combined <- vegan::vegdist(data_combined,
                                      method = "bray")
      fit_pcoa <- ape::pcoa(dist_combined)
      tb_plot <- 
        fit_pcoa$vectors %>% 
        tibble::as_tibble() %>% 
        dplyr::mutate(class =
                        c(rep("Original", nrow(data)),
                          rep("SparseDOSSA", 1000)) %>% 
                        forcats::as_factor())
      fit_pnova <- vegan::adonis(dist_combined ~ class,
                                 data = tb_plot,
                                 permutations = 2)
      p <- tb_plot %>% 
        dplyr::arrange(-as.numeric(class)) %>% 
        ggplot(aes(x = Axis.1, y = Axis.2, color = class)) +
        geom_point() +
        theme_bw() +
        coord_fixed() +
        xlab(paste0("PCo1 (", round(fit_pcoa$values[1, 2] * 100, 2), "%)")) +
        ylab(paste0("PCo2 (", round(fit_pcoa$values[2, 2] * 100, 2), "%)")) +
        ggtitle(paste0(i_name, "\n",
                       "R2 = ", round(fit_pnova$aov.tab[1, 5] * 100, 2), "%"))
      ggsave(paste0(dir_output, "ord_", i_name, "_mvn.pdf"),
             p,
             width = 6, height = 6)
    })
```

```{r compare dmm fit vs original}
fit_vaginal_dmm <- dmm(data = x_samples_vaginal, ks = 3)
save(fit_vaginal_dmm, file = paste0(dir_output, "fit_vaginal_dmm.RData"))
fit_stool_dmm <- dmm(data = x_samples_stool, ks = 3)
save(fit_stool_dmm, file = paste0(dir_output, "fit_stool_dmm.RData"))
set.seed(1)
c("Vaginal", "Stool") %>% 
  purrr::map2(
    c(1, 2),
    function(i_name, i) {
      data <- list(x_samples_vaginal, x_samples_stool)[[i]]
      fit_model <- list(fit_vaginal_mvn, fit_stool_mvn)[[i]]
      a_samples <- 
        mvtnorm::rmvnorm(
          n = 1000,
          mean = fit_model$l_fits[[1]]$fit$mu,
          sigma = 
            diag(sqrt(fit_model$l_fits[[1]]$fit$sigma)) %*%
            fit_model$l_fits[[1]]$fit$Sigma %*%
            diag(sqrt(fit_model$l_fits[[1]]$fit$sigma))
        )
      a_samples <- exp(a_samples) / (1 + exp(a_samples))
      a_samples <- a_samples[!apply(a_samples == 0, 1, all), ][seq_len(1000), ]
      x_samples <- apply(a_samples, 1, TSS) %>% t()
      data_combined <- rbind(data, x_samples)
      dist_combined <- vegan::vegdist(data_combined,
                                      method = "bray")
      fit_pcoa <- ape::pcoa(dist_combined)
      tb_plot <- 
        fit_pcoa$vectors %>% 
        tibble::as_tibble() %>% 
        dplyr::mutate(class =
                        c(rep("Original", nrow(data)),
                          rep("SparseDOSSA", 1000)) %>% 
                        forcats::as_factor())
      fit_pnova <- vegan::adonis(dist_combined ~ class,
                                 data = tb_plot,
                                 permutations = 2)
      p <- tb_plot %>% 
        dplyr::arrange(-as.numeric(class)) %>% 
        ggplot(aes(x = Axis.1, y = Axis.2, color = class)) +
        geom_point() +
        theme_bw() +
        coord_fixed() +
        xlab(paste0("PCo1 (", round(fit_pcoa$values[1, 2] * 100, 2), "%)")) +
        ylab(paste0("PCo2 (", round(fit_pcoa$values[2, 2] * 100, 2), "%)")) +
        ggtitle(paste0(i_name, ", ", "LogitMVN\n",
                       "R2 = ", round(fit_pnova$aov.tab[1, 5] * 100, 2), "%"))
      ggsave(paste0(dir_output, "ord_", i_name, "_mvn.pdf"),
             p,
             width = 6, height = 6)
    })
```

```{r proof of concept spike in}
data <- x_samples_stool
features_top_abd <- 
  colnames(x_samples_stool)[order(-apply(x_samples_stool, 2, mean))[1:20]]
fit_spd <- fit_stool
a_samples <- simulate_a(n = 2000,
                        params = fit_spd$l_fits_full[[1]]$fit)
a_samples <- a_samples[!apply(a_samples == 0, 1, all), ][seq_len(1000), ]
colnames(a_samples) <- colnames(x_samples_stool)
x_samples <- apply(a_samples, 1, TSS) %>% t()
colnames(x_samples) <- colnames(x_samples_stool)

pheno_samples <- rep(c(0, -1), each = 500)
effect_size <- 2
which_feature <- which(colnames(x_samples_stool) == features_top_abd[10])
params_spike <- list(pi0 = fit_spd$l_fits_full[[1]]$fit$pi0[which_feature],
                     mu = fit_spd$l_fits_full[[1]]$fit$mu[which_feature],
                     sigma = fit_spd$l_fits_full[[1]]$fit$sigma[which_feature])
pi0s_spiked <- effect_size * pheno_samples + log(params_spike$pi0) - log(1 - params_spike$pi0)
pi0s_spiked <- exp(pi0s_spiked) / (1 + exp(pi0s_spiked))
mus_spiked <- params_spike$mu + effect_size * pheno_samples

set.seed(1)
a_samples_pi0_spiked <- 
  a_samples_mu_spiked <- 
  a_samples
a_samples_pi0_spiked[, which_feature] <- 
  rbinom(n = 1000, size = 1, prob = pi0s_spiked) *
  exp(rnorm(n = 1000, mean = params_spike$mu, sd = params_spike$sigma))
a_samples_mu_spiked[, which_feature] <- 
  rbinom(n = 1000, size = 1, prob = params_spike$pi0) *
  exp(rnorm(n = 1000, mean = mus_spiked, sd = params_spike$sigma))

# plotting
x_samples_stool_plot <- 
  x_samples_stool[order(x_samples_stool[, which_feature]), features_top_abd][, c(10, setdiff(1:20, 10))]
tb_samples_stool_plot <- 
  tibble::as_tibble(x_samples_stool_plot) %>% 
  dplyr::mutate(Sample = paste0("Sample", seq_len(dplyr::n())) %>% 
                  forcats::as_factor()) %>% 
  tidyr::pivot_longer(cols = colnames(x_samples_stool_plot), 
                      names_to = "Feature",
                      values_to = "Abundance") %>% 
  dplyr::mutate(Feature = factor(Feature, levels = rev(colnames(x_samples_stool_plot))))
p <- tb_samples_stool_plot %>% 
  ggplot(aes(x = Sample, y = Feature, fill = log10(Abundance))) +
  scale_fill_gradient(low = "darkblue", high = "red", na.value = "black") +
  geom_tile() +
  theme_bw() +
  theme(axis.title = element_blank(),
        axis.text = element_blank(), 
        axis.ticks = element_blank())
ggsave(paste0(dir_output, "heatmap_data.pdf"),
     p,
     width = 10, height = 6)
  
x_samples_null_plot <- 
  rbind(x_samples[seq(1, 500),
                  features_top_abd][order(x_samples[seq(1, 500), which_feature]),],
        x_samples[seq(501, 1000),
                  features_top_abd][order(x_samples[seq(501, 1000), which_feature]),])[, c(10, setdiff(1:20, 10))]
tb_samples_null_plot <- 
  tibble::as_tibble(x_samples_null_plot) %>% 
  dplyr::mutate(Sample = paste0("Sample", seq_len(dplyr::n())) %>% 
                  forcats::as_factor()) %>% 
  tidyr::pivot_longer(cols = colnames(x_samples_null_plot), 
                      names_to = "Feature",
                      values_to = "Abundance") %>% 
  dplyr::mutate(Feature = factor(Feature, levels = rev(colnames(x_samples_null_plot))))
p <- tb_samples_null_plot %>% 
  ggplot(aes(x = Sample, y = Feature, fill = log10(Abundance))) +
  scale_fill_gradient(low = "darkblue", high = "red", na.value = "black") +
  geom_tile() +
  theme_bw() +
  theme(axis.title = element_blank(),
        axis.text = element_blank(), 
        axis.ticks = element_blank())
ggsave(paste0(dir_output, "heatmap_null.pdf"),
     p,
     width = 10, height = 6)

x_samples_pi0 <- apply(a_samples_pi0_spiked, 1, TSS) %>% t()
colnames(x_samples_pi0) <- colnames(x_samples_stool)
x_samples_pi0_plot <- 
  rbind(x_samples_pi0[seq(1, 500),
                  features_top_abd][order(x_samples_pi0[seq(1, 500), which_feature]),],
        x_samples_pi0[seq(501, 1000),
                  features_top_abd][order(x_samples_pi0[seq(501, 1000), which_feature]),])[, c(10, setdiff(1:20, 10))]
p <- tb_samples_pi0_plot <- 
  tibble::as_tibble(x_samples_pi0_plot) %>% 
  dplyr::mutate(Sample = paste0("Sample", seq_len(dplyr::n())) %>% 
                  forcats::as_factor()) %>% 
  tidyr::pivot_longer(cols = colnames(x_samples_pi0_plot), 
                      names_to = "Feature",
                      values_to = "Abundance") %>% 
  dplyr::mutate(Feature = factor(Feature, levels = rev(colnames(x_samples_pi0_plot))))
p <- tb_samples_pi0_plot %>% 
  ggplot(aes(x = Sample, y = Feature, fill = log10(Abundance))) +
  scale_fill_gradient(low = "darkblue", high = "red", na.value = "black") +
  geom_tile() +
  theme_bw() +
  theme(axis.title = element_blank(),
        axis.text = element_blank(), 
        axis.ticks = element_blank())
ggsave(paste0(dir_output, "heatmap_pi0.pdf"),
     p,
     width = 10, height = 6)


x_samples_mu <- apply(a_samples_mu_spiked, 1, TSS) %>% t()
colnames(x_samples_mu) <- colnames(x_samples_stool)
x_samples_mu_plot <- 
  rbind(x_samples_mu[seq(1, 500),
                  features_top_abd][order(x_samples_mu[seq(1, 500), which_feature]),],
        x_samples_mu[seq(501, 1000),
                  features_top_abd][order(x_samples_mu[seq(501, 1000), which_feature]),])[, c(10, setdiff(1:20, 10))]
tb_samples_mu_plot <- 
  tibble::as_tibble(x_samples_mu_plot) %>% 
  dplyr::mutate(Sample = paste0("Sample", seq_len(dplyr::n())) %>% 
                  forcats::as_factor()) %>% 
  tidyr::pivot_longer(cols = colnames(x_samples_mu_plot), 
                      names_to = "Feature",
                      values_to = "Abundance") %>% 
  dplyr::mutate(Feature = factor(Feature, levels = rev(colnames(x_samples_mu_plot))))
p <- tb_samples_mu_plot %>% 
  ggplot(aes(x = Sample, y = Feature, fill = log10(Abundance))) +
  scale_fill_gradient(low = "darkblue", high = "red", na.value = "black") +
  geom_tile() +
  theme_bw() +
  theme(axis.title = element_blank(),
        axis.text = element_blank(), 
        axis.ticks = element_blank())
ggsave(paste0(dir_output, "heatmap_mu.pdf"),
     p,
     width = 10, height = 6)
```