---
title: "Test dloga to see if it's really the density"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/n/janson_lab/lab/sma/sparsedossa_update/")
knitr::opts_chunk$set(echo=FALSE)
library(magrittr)
library(ggplot2)
```

```{r dlogas for two d situation}
smar::sourceDir("SparseDOSSA2/R/")
pi0 <- c(0.2, 0.8)
mu <- c(0, 0)
sigma <- c(1, 2)
Sigma <- matrix(c(1, 0.5, 0.5, 1), 2, 2)
Omega <- solve(Sigma)

integrate(
  function(x) {
    sapply(x, 
           function(i_loga)
             dloga(a = c(0, exp(i_loga)),
                   pi0 = pi0,
                   mu = mu,
                   sigma = sigma,
                   Omega = Omega,
                   Sigma = Sigma, 
                   log.p = FALSE))
  },
  lower = -10,
  upper = 10)

mvtnorm::pmvnorm(lower = c(-Inf, qnorm(pi0[2])), 
                 upper = c(qnorm(pi0[1]), Inf), 
                 corr =  Sigma)

v_loga <- seq(-10, 10, by = 0.01)
v_dloga <- sapply(v_loga,
                  function(i_loga)
                    dloga(a = c(0, exp(i_loga)),
                          pi0 = pi0,
                          mu = mu,
                          sigma = sigma,
                          Omega = Omega,
                          Sigma = Sigma, 
                          log.p = FALSE))

plot(v_loga, v_dloga)
samples_a <- simulate_a(n = 1000000,
                        params = list(pi0 = pi0, 
                                      mu = mu,
                                      sigma = sigma,
                                      Omega = Omega))
samples_a_sub <- samples_a[samples_a[, 1] == 0 &
                             samples_a[, 2] > 0, ]
hist(log(samples_a_sub[, 2]), breaks = 100)

load("results/tmp/2020_05_26_debug_EM/1/debug_lambda_1.RData")
params <- l_debug$ll_params[[1]]
pi0 <- params$pi0[46:50]
mu <- params$mu[46:50]
sigma <- params$sigma[46:50]
Sigma <- params$Sigma[46:50, 46:50]
Omega <- solve(Sigma)

set.seed(1)
samples_a <- simulate_a(n = 50,
                        params = list(pi0 = pi0, 
                                      mu = mu,
                                      sigma = sigma,
                                      Omega = Omega))
samples_a <- samples_a[!apply(samples_a == 0, 1, all), ]
samples_x <- apply(samples_a, 1, function(x) x / sum(x)) %>% t()

fit_EM <- EM_diagnose(
    data = samples_x,
    lambdas = 1e-4,
    control = list(abs_tol = 1e-3,
                   rel_tol = 1,
                   maxit = 100,
                   verbose = TRUE,
                   debug_dir = paste0(dir_output, i_job, "/"),
                   control_numint = list(rel_tol = 1e-3,
                                         abs_tol = 0,
                                         max_eval = 50)))
```