---
title: "Test multiple partition"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/n/janson_lab/lab/sma/sparsedossa_update/")
knitr::opts_chunk$set(echo=FALSE)
library(magrittr)
library(ggplot2)
```

```{r setup2, include=FALSE}
# Registry
# batchtools::makeRegistry(file.dir = "r_batchtools_reg/test_partition/",
#                          package = "magrittr")
batchtools::loadRegistry(file.dir = "r_batchtools_reg/test_partition/", 
                         writeable = TRUE)
batchtools::clearRegistry()

# Grid parameters
ncpus <- 20
partition <- "janson_cascade,janson"
walltime <- 60
```

```{r job grid}
tb_job <- tibble::tibble(
  i_job = seq(1, 20)
)
```

```{r load datasets}
one_job <- function(i_job) {
  Sys.sleep(30)
}
```

```{r submit jobs}
time_start <- Sys.time()
tb_ids <- batchtools::batchMap(one_job, 
                               i_job = tb_job$i_job)
batchtools::batchExport(mget(ls()))
batchtools::submitJobs(ids = tb_ids$ids,
                       resources =  list(ncpus = ncpus, 
                                         partition = partition, 
                                         walltime = walltime))
print(Sys.time() - time_start)
```