---
title: "Format the datasets used in this paper"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---
```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_knit$set(root.dir = normalizePath(".."))
```
```{r source functions, include=FALSE}
smar::sourceDir("../ibd_paper/functions/")
smar::set_ggplot()
library(magrittr)
library(ggplot2)
```

```{r create HMP1-II stool and vaginal datasets}
# metadata
metaphlan_log <- read.delim("data/hmp1-II/hmp1-II_humann2_logs-mtd.pcl",
                            sep = "\t",
                            check.names = FALSE,
                            stringsAsFactors = FALSE)
df_metadata <- metaphlan_log %>% 
  t() %>% 
  as.data.frame(check.names = FALSE, stringsAsFactors = FALSE) %>% 
  set_colnames(unlist(.[1, ])) %>% 
  dplyr::slice(-1)
df_metadata <- df_metadata %>% 
  dplyr::mutate(READS_initial = as.integer(READS_initial),
                READS_pangenomes_aligned = as.integer(READS_pangenomes_aligned),
                READS_pangenomes_aligned_frac = 
                  as.numeric(READS_pangenomes_aligned_frac),
                read_depth = READS_initial * 0.05)
# need to set rownames as dplyr discards them
df_metadata <- df_metadata %>% 
  set_rownames(colnames(metaphlan_log)[-1])

# abd matrix
metaphlan <- read.delim("data/hmp1-II/hmp1-II_metaphlan2-mtd-qcd.pcl",
                        sep = "\t",
                        check.names = FALSE,
                        stringsAsFactors = FALSE)
mat_abd <- metaphlan[-(1:8), -1] %>% 
  as.matrix %>% 
  apply(2, as.numeric) %>% 
  set_rownames(metaphlan[-(1:8), 1])

# common samples
samples_common <- intersect(rownames(df_metadata),
                            colnames(mat_abd))
physeq_all <- phyloseq::phyloseq(phyloseq::otu_table(mat_abd[, samples_common], 
                                                    taxa_are_rows = TRUE),
                                phyloseq::sample_data(
                                  df_metadata[samples_common, ]))
taxa_bacteria <- phyloseq::taxa_names(physeq_all) %>% 
  stringr::str_subset(stringr::fixed("k__Bacteria"))
physeq_all <- physeq_all %>% 
  phyloseq::prune_taxa(taxa_bacteria, .)

# species level data
physeq_species <- phyloseq::taxa_names(physeq_all) %>% 
  {and(stringr::str_detect(., stringr::fixed("|s__")),
       !stringr::str_detect(., stringr::fixed("|t__")))} %>% 
  phyloseq::prune_taxa(physeq_all)

# transform to counts
df_meta <- smar::sample_data2(physeq_species)
mat_otu <- smar::otu_table2(physeq_species) %>% 
  t() %>% `*`(df_meta$read_depth) %>% t() %>% 
  round()
df_meta$read_depth <- apply(mat_otu, 2, sum)
mat_taxa <- phyloseq::taxa_names(physeq_species) %>% 
  stringr::str_split_fixed(stringr::fixed("|"), n = 7)
dimnames(mat_taxa) <- list(
  phyloseq::taxa_names(physeq_species),
  paste0("Rank", 1:7)
)
physeq_species <- phyloseq::phyloseq(
  phyloseq::otu_table(mat_otu, taxa_are_rows = TRUE),
  phyloseq::sample_data(df_meta),
  phyloseq::tax_table(mat_taxa)
) %>% 
  smar::prune_taxaSamples()
physeq_stool <- physeq_species %>% 
  phyloseq::subset_samples(STSite == "Stool") %>% 
  smar::prune_taxaSamples()
physeq_vaginal <- physeq_species %>% 
  phyloseq::subset_samples(STSite == "Posterior_fornix") %>% 
  smar::prune_taxaSamples()

save(physeq_species, file = "data/physeqs/HMP1II_all.RData")
save(physeq_stool, file = "data/physeqs/HMP1II_stool.RData")
save(physeq_vaginal, file = "data/physeqs/HMP1II_vaginal.RData")
```

```{r format Pouchitis}
load("../ibd_paper/data/physeq/Pouchitis/species.RData")
physeq_pouchitis <- physeq_species %>% 
  phyloseq::subset_samples(disease == "UC")
mat_otu <- smar::otu_table2(physeq_pouchitis)
mat_taxa <- smar::tax_table2(physeq_pouchitis)[, 1:7]
rownames(mat_otu) <- rownames(mat_taxa) <- 
  apply(mat_taxa, 1, paste, collapse = "|")
df_meta <- smar::sample_data2(physeq_pouchitis)
df_meta$read_depth <- apply(mat_otu, 2, sum)
physeq_pouchitis <- phyloseq::phyloseq(
  phyloseq::otu_table(mat_otu, taxa_are_rows = TRUE),
  phyloseq::sample_data(df_meta),
  phyloseq::tax_table(mat_taxa)
) %>% 
  phyloseq::subset_samples(read_depth > 3000) %>% 
  smar::prune_taxaSamples()
save(physeq_pouchitis, file = "data/physeqs/Pouchitis.RData")
```