---
title: "Format the datasets used in this paper"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---
```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_knit$set(root.dir = normalizePath(".."))
```
```{r source functions, include=FALSE}
smar::sourceDir("../ibd_paper/functions/")
smar::set_ggplot()
library(magrittr)
library(ggplot2)
dir_output <- "results/2-validate_cohorts"
dir.create(dir_output, recursive = TRUE)
```

```{r load datasets}
load("data/physeqs/HMP1II_stool.RData")
load("data/physeqs/HMP1II_vaginal.RData")
load("data/physeqs/Pouchitis.RData")
l_physeqs <- list(physeq_stool, physeq_vaginal, physeq_pouchitis)
dataset_names <- c("HMP1-II Stool", "HMP1-II Vaginal", "Pouchitis")
```

```{r fit SparseDOSSA and plot}
for(i in 1:length(l_physeqs)) {
  physeq <- l_physeqs[[i]]
  name_physeq <- dataset_names[i]
  n_i <- smar::sample_data2(physeq)$read_depth
  feature_abd <- smar::otu_table2(physeq)
  
  # run sparseDOSSA estimation and simulation
  fit_sparseDOSSA <- SparseDOSSA2::SparseDOSSA2(n_sample = ncol(feature_abd),
                                                n_feature = nrow(feature_abd),
                                                template = feature_abd,
                                                same_features = FALSE,
                                                feature_feature_association = FALSE,
                                                read_depth = median(n_i))
  save(fit_sparseDOSSA, file = paste0(dir_output, "fit_", name_physeq, ".RData"))
  
  
  # combine the two together
  matOTU_combined <- cbind(feature_abd[order(apply(feature_abd, 2, MMUPHin:::tss) %>% 
                                               apply(1, mean),
                                             decreasing = TRUE), ],
                           fit_sparseDOSSA$counts[order(apply(fit_sparseDOSSA$counts, 2, MMUPHin:::tss) %>% 
                                                          apply(1, mean),
                                                        decreasing = TRUE), ])
  rownames(matOTU_combined) <- paste0("Feature", 1:nrow(matOTU_combined))
  dfMeta_combined <- data.frame(Sample = rep(c(name_physeq,
                                               "SparseDOSSA"),
                                             each = ncol(feature_abd))%>% 
                                  forcats::fct_inorder())
  rownames(dfMeta_combined) <- colnames(matOTU_combined)
  dfMeta_combined$sample_name <- rownames(dfMeta_combined)
  
  # ordination visualization
  dist_all <- matOTU_combined %>% 
    phyloseq::otu_table(taxa_are_rows = TRUE) %>% 
    phyloseq::transform_sample_counts(MMUPHin:::tss) %>% 
    phyloseq::distance(method = "bray")
  ordination <- matOTU_combined %>% 
    phyloseq::otu_table(taxa_are_rows = TRUE) %>% 
    phyloseq::ordinate(method = "MDS", distance = dist_all)
  axes.labels <- paste0(c("Axis 1 (", "Axis 2 ("), 
                        round(ordination$values$Relative_eig[1:2] * 100, digits = 1), 
                        "%)")
  tb_plot <- ordination$vectors[, 1:2] %>% 
    as.data.frame() %>% 
    dplyr::bind_cols(dfMeta_combined)
  
  pval <- vegan::adonis(dist_all ~ Sample, data = tb_plot, permutations = 999)
  
  colors <- c("black", "red")
  names(colors) <- c(name_physeq, "SparseDOSSA")
  p_ordinate <- tb_plot %>% 
    ggplot(aes(x = Axis.1, y = Axis.2)) +
    geom_point(aes(color = Sample)) +
    scale_color_manual(values = colors, name = NULL) +
    theme(legend.position = c(0, 1),
          legend.justification = c(0, 1),
          legend.background = element_blank()) +
    coord_fixed() +
    xlab(axes.labels[1]) + ylab(axes.labels[2]) +
    theme(axis.text = element_blank(), axis.ticks = element_blank()) +
    ggtitle(paste0("PERMANOVA p = ", pval$aov.tab$`Pr(>F)`[1]))
  
  # heatmap visualization
  nFeatures_heatmap <- 20
  tb_heatmap <- matOTU_combined %>% 
    apply(2, MMUPHin:::tss) %>% 
    `[`(1:nFeatures_heatmap, ) %>% 
    {log10(. + 1e-5)} %>% 
    t() %>% 
    as.data.frame() %>% 
    tibble::rownames_to_column("sample_name") %>% 
    dplyr::left_join(dfMeta_combined, by = "sample_name") %>% 
    dplyr::arrange(Sample, -Feature1, -Feature2, -Feature3, -Feature4, 
                   -Feature5, -Feature6, -Feature7, -Feature8) %>% 
    dplyr::mutate(sample_name = sample_name %>% forcats::fct_inorder()) %>% 
    tidyr::gather(key = "feature", value = "Abundance", -sample_name, -Sample) %>% 
    dplyr::mutate(feature = factor(feature, levels = paste0("Feature", nFeatures_heatmap:1)))
  tb_separate <- data.frame(x = ncol(feature_abd),
                            y = -0.5,
                            yend = nFeatures_heatmap + 1.5)
  p_heatmap <- tb_heatmap %>% 
    ggplot() +
    geom_tile(data = tb_heatmap, 
              aes(x = sample_name, y = feature,
                  fill = Abundance)) +
    scale_fill_gradient(low = "black", high = "red", name = "log 10 abundance") +
    theme(axis.title = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank(),
          panel.border = element_blank(),
          legend.position = "top", legend.direction = "horizontal") +
    coord_cartesian(clip = 'off') +
    annotate("segment", 
             x = ncol(feature_abd),
             xend = ncol(feature_abd),
             y = 0.5,
             yend = nFeatures_heatmap + 0.5,
             size = 1, linetype = "dashed", color = "white") +
    annotate("text", x = ncol(feature_abd), y = nFeatures_heatmap + 0.5,
             hjust = 1.1, vjust = 1.1, label = name_physeq, size = 5,
             color = "white") +
    annotate("text", x = ncol(feature_abd), y = nFeatures_heatmap + 0.5,
             hjust = -0.1, vjust = 1.1, label = "SparseDOSSA", size = 5,
             color = "white")
  
  # p distributions
  tb_params <- list(feature_abd,
                    fit_sparseDOSSA$counts) %>% 
    purrr::map2_dfr(c(name_physeq, "SparseDOSSA"),
                    function(mat_otu, i_Sample) {
                      tb_features <- mat_otu %>% 
                        apply(2, MMUPHin:::tss) %>% 
                        as.data.frame() %>% 
                        dplyr::mutate(feature = paste0("Feature", 1:dplyr::n())) %>% 
                        tidyr::gather(key = "sample_name", value = "Abundance", 
                                      -feature) %>% 
                        dplyr::group_by(feature) %>% 
                        dplyr::summarise(Prevalence = log(mean(Abundance > 0)) - log(1 - mean(Abundance > 0)),
                                         `Mean abundance` = mean(log(Abundance[Abundance > 0]) - 
                                                                   log(1 - Abundance[Abundance > 0])),
                                         `Variance` = ifelse(sum(Abundance > 0) > 1,
                                                             var(log(Abundance[Abundance > 0]) - 
                                                                   log(1 - Abundance[Abundance > 0])),
                                                             0)) %>% 
                        dplyr::mutate(Sample = i_Sample)
                    }) %>% 
    dplyr::mutate(Sample = Sample %>% forcats::fct_inorder()) %>% 
    tidyr::gather(key = "Parameter",
                  value = "Value",
                  Prevalence, `Mean abundance`, Variance) %>% 
    dplyr::mutate(Parameter = Parameter %>% forcats::fct_inorder())
  p_dist <- tb_params %>% 
    ggplot(aes(x = Value)) +
    geom_density(aes(color = Sample, fill = Sample), alpha = 0.1) +
    scale_color_manual(values = colors, name = NULL) + 
    scale_fill_manual(values = colors, name = NULL) +
    facet_grid(.~Parameter, scales = "free_x") +
    theme(axis.title.x = element_blank(),
          legend.position = c(1, 1),
          legend.justification = c(1, 1),
          legend.background = element_blank())
  
  p_cohort <- cowplot::plot_grid(p_ordinate, p_heatmap, nrow = 1, align = "h", axis = "tb",
                                 rel_widths = c(1, 1.5)) %>% 
    cowplot::plot_grid(p_dist, ncol = 1, rel_heights = c(1.5, 1))
  save(p_cohort, file = paste0(dir_output, "figure_", name_physeq, ".RData"))
}
l_ps <- list()
for(i in 1:3) {
  load(paste0(dir_output, "figure_", dataset_names[i], ".Rdata"))
  l_ps[[i]] <- p_cohort
}
cowplot::plot_grid(plotlist = l_ps, labels = paste0(c("A) ", "B) ", "C) "), dataset_names),
                   nrow = 3,
                   label_fontface = "plain",
                   label_x = 0,
                   label_size = 20,
                   hjust = 0) %>% 
  ggsave(file = "figures/fig_evaluation/fig_evaluation.pdf", .,
         width = 15, height = 30)
```

```{r plotting}
l_ordinate <- l_heatmap <- l_param <- list()
l_zero <- list()
for(i in 1:length(l_physeqs)) {
  physeq <- l_physeqs[[i]]
  name_physeq <- dataset_names[i]
  
  load(paste0(dir_output, "fit_", name_physeq, ".RData"))
  
  n_i <- smar::sample_data2(physeq)$read_depth
  feature_abd <- smar::otu_table2(physeq)
  
  tb_zeros <- data.frame(SparseDOSSA2 = fit_sparseDOSSA$template_fits$em %>%
                           purrr::map_dbl(~.x$theta["pi"]),
                         Original = apply(feature_abd != 0, 1, mean))
  p_zero <- tb_zeros %>% 
    ggplot(aes(x = Original, y = SparseDOSSA2)) +
    geom_point() +
    xlab("Original") + ylab("SparseDOSSA2") +
    ggtitle(name_physeq)
  l_zero[[i]] <- p_zero
  # combine the two together
  # matOTU_combined <- cbind(feature_abd[order(apply(feature_abd, 2, MMUPHin:::tss) %>% 
  #                                           apply(1, mean),
  #                                         decreasing = TRUE), ],
  #                       fit_sparseDOSSA$counts[order(apply(fit_sparseDOSSA$counts, 2, MMUPHin:::tss) %>% 
  #                                                      apply(1, mean),
  #                                                    decreasing = TRUE), ])
  # rownames(matOTU_combined) <- paste0("Feature", 1:nrow(matOTU_combined))
  # dfMeta_combined <- data.frame(Sample = rep(c(name_physeq,
  #                                              "SparseDOSSA"),
  #                                            each = ncol(feature_abd))%>% 
  #                                              forcats::fct_inorder())
  # rownames(dfMeta_combined) <- colnames(matOTU_combined)
  # dfMeta_combined$sample_name <- rownames(dfMeta_combined)
  # 
  # # ordination visualization
  # dist_all <- matOTU_combined %>% 
  #   phyloseq::otu_table(taxa_are_rows = TRUE) %>% 
  #   phyloseq::transform_sample_counts(MMUPHin:::tss) %>% 
  #   phyloseq::distance(method = "bray")
  # ordination <- matOTU_combined %>% 
  #   phyloseq::otu_table(taxa_are_rows = TRUE) %>% 
  #   phyloseq::ordinate(method = "MDS", distance = dist_all)
  # axes.labels <- paste0(c("Axis 1 (", "Axis 2 ("), 
  #                       round(ordination$values$Relative_eig[1:2] * 100, digits = 1), 
  #                       "%)")
  # tb_plot <- ordination$vectors[, 1:2] %>% 
  #   as.data.frame() %>% 
  #   dplyr::bind_cols(dfMeta_combined)
  # 
  # pval <- vegan::adonis(dist_all ~ Sample, data = tb_plot, permutations = 999)
  # 
  # colors <- c("black", "red")
  # names(colors) <- c(name_physeq, "SparseDOSSA")
  # p_ordinate <- tb_plot %>% 
  #   ggplot(aes(x = Axis.1, y = Axis.2)) +
  #   geom_point(aes(color = Sample)) +
  #   scale_color_manual(values = colors, name = NULL) +
  #   theme(legend.position = c(0, 1),
  #         legend.justification = c(0, 1),
  #         legend.background = element_blank()) +
  #   coord_fixed() +
  #   xlab(axes.labels[1]) + ylab(axes.labels[2]) +
  #   theme(axis.text = element_blank(), axis.ticks = element_blank()) +
  #   ggtitle(paste0("R2 = ", round(pval$aov.tab$R2[1], digits = 3),
  #                  ifelse(pval$aov.tab$R2[1] < 0.05, "*", "")))
  # l_ordinate[[i]] <- p_ordinate
  # 
  # # heatmap visualization
  # nFeatures_heatmap <- 20
  # tb_heatmap <- matOTU_combined %>% 
  #   apply(2, MMUPHin:::tss) %>% 
  #   `[`(1:nFeatures_heatmap, ) %>% 
  #   {log10(. + 1e-5)} %>% 
  #   t() %>% 
  #   as.data.frame() %>% 
  #   tibble::rownames_to_column("sample_name") %>% 
  #   dplyr::left_join(dfMeta_combined, by = "sample_name") %>% 
  #   dplyr::arrange(Sample, -Feature1, -Feature2, -Feature3, -Feature4, 
  #                  -Feature5, -Feature6, -Feature7, -Feature8) %>% 
  #   dplyr::mutate(sample_name = sample_name %>% forcats::fct_inorder()) %>% 
  #   tidyr::gather(key = "feature", value = "Abundance", -sample_name, -Sample) %>% 
  #   dplyr::mutate(feature = factor(feature, levels = paste0("Feature", nFeatures_heatmap:1)))
  # tb_separate <- data.frame(x = ncol(feature_abd),
  #                           y = -0.5,
  #                           yend = nFeatures_heatmap + 1.5)
  # p_heatmap <- tb_heatmap %>% 
  #   ggplot() +
  #   geom_tile(data = tb_heatmap, 
  #             aes(x = sample_name, y = feature,
  #                 fill = Abundance)) +
  #   scale_fill_gradient(low = "black", high = "red", name = "log 10 abundance") +
  #   theme(axis.title = element_blank(),
  #         axis.text = element_blank(),
  #         axis.ticks = element_blank(),
  #         panel.border = element_blank(),
  #         legend.position = "top", legend.direction = "horizontal") +
  #   coord_cartesian(clip = 'off') +
  #   annotate("segment", 
  #            x = ncol(feature_abd),
  #            xend = ncol(feature_abd),
  #            y = 0.5,
  #            yend = nFeatures_heatmap + 0.5,
  #            size = 1, linetype = "dashed", color = "white") +
  #   annotate("text", x = ncol(feature_abd), y = nFeatures_heatmap + 0.5,
  #            hjust = 1.1, vjust = 1.1, label = name_physeq, size = 5,
  #            color = "white") +
  #   annotate("text", x = ncol(feature_abd), y = nFeatures_heatmap + 0.5,
  #            hjust = -0.1, vjust = 1.1, label = "SparseDOSSA", size = 5,
  #            color = "white")
  # l_heatmap[[i]] <- p_heatmap
  # 
  # # p distributions
  # tb_params <- list(feature_abd,
  #                   fit_sparseDOSSA$counts) %>% 
  #   purrr::map2_dfr(c(name_physeq, "SparseDOSSA"),
  #               function(mat_otu, i_Sample) {
  #                 tb_features <- mat_otu %>% 
  #                   apply(2, MMUPHin:::tss) %>% 
  #                   as.data.frame() %>% 
  #                   dplyr::mutate(feature = paste0("Feature", 1:dplyr::n())) %>% 
  #                   tidyr::gather(key = "sample_name", value = "Abundance", 
  #                                 -feature) %>% 
  #                   dplyr::group_by(feature) %>% 
  #                   dplyr::summarise(Prevalence = log(mean(Abundance > 0)) - log(1 - mean(Abundance > 0)),
  #                                    `Mean abundance` = mean(log(Abundance[Abundance > 0]) - 
  #                                                              log(1 - Abundance[Abundance > 0])),
  #                                    `Variance` = ifelse(sum(Abundance > 0) > 1,
  #                                                        var(log(Abundance[Abundance > 0]) - 
  #                                                              log(1 - Abundance[Abundance > 0])),
  #                                                        0)) %>% 
  #                   dplyr::mutate(Sample = i_Sample)
  #               }) %>% 
  #   dplyr::mutate(Sample = Sample %>% forcats::fct_inorder()) %>% 
  #   tidyr::gather(key = "Parameter",
  #                 value = "Value",
  #                 Prevalence, `Mean abundance`, Variance) %>% 
  #   dplyr::mutate(Parameter = Parameter %>% forcats::fct_inorder())
  # p_dist <- tb_params %>% 
  #   ggplot(aes(x = Value)) +
  #   geom_density(aes(color = Sample, fill = Sample), alpha = 0.1) +
  #   scale_color_manual(values = colors, name = NULL) + 
  #   scale_fill_manual(values = colors, name = NULL) +
  #   facet_grid(.~Parameter, scales = "free_x") +
  #   theme(axis.title.x = element_blank(),
  #         legend.position = c(1, 1),
  #         legend.justification = c(1, 1),
  #         legend.background = element_blank())
  # l_param[[i]] <- p_dist
}
cowplot::plot_grid(plotlist = l_ordinate, labels = dataset_names, nrow = 1,
                   label_fontface = "plain", hjust = 0) %>% 
  ggsave("results/2-validate_cohorts/ordination.pdf", ., width = 12, height = 5)
cowplot::plot_grid(plotlist = l_heatmap, nrow = 1) %>% 
  ggsave("results/2-validate_cohorts/heatmap.pdf", ., width = 15, height = 5)
cowplot::plot_grid(plotlist = l_param, nrow = 3) %>% 
  ggsave("results/2-validate_cohorts/param.pdf", ., width = 12, height = 12)
cowplot::plot_grid(plotlist = l_zero[c(1, 3)]) %>% 
  ggsave("results/2-validate_cohorts/zeros.pdf", ., width = 12, height = 6)

```

```{r more systematic evaluations}
R <- 100
for(i in 1) {
  physeq <- l_physeqs[[i]]
  name_physeq <- dataset_names[i]
  n_i <- smar::sample_data2(physeq)$read_depth
  feature_abd <- smar::otu_table2(physeq)
  
  # run sparseDOSSA estimation and simulation
  fit_sparseDOSSA <- SparseDOSSA2::SparseDOSSA2(n_sample = ncol(feature_abd),
                                                n_feature = nrow(feature_abd),
                                                template = feature_abd,
                                                same_features = FALSE,
                                                feature_feature_association = FALSE,
                                                read_depth = median(n_i))
  fit_sparseDOSSA2 <- SparseDOSSA2::SparseDOSSA2(n_sample = ncol(feature_abd),
                                                 template = feature_abd,
                                                 same_features = TRUE,
                                                 feature_feature_association = FALSE,
                                                 read_depth = median(n_i))
  
  # combine the two together
  matOTU_combined1 <- cbind(
    feature_abd[
      order(apply(feature_abd, 2, 
                  function(x) x / sum(x)) %>% 
              apply(1, mean),
            decreasing = TRUE), ],
    fit_sparseDOSSA$counts[
      order(apply(fit_sparseDOSSA$counts, 2, 
                  function(x) x / sum(x)) %>% 
              apply(1, mean),
            decreasing = TRUE), ])
  rownames(matOTU_combined1) <- paste0("Feature", 1:nrow(matOTU_combined1))
  
  matOTU_combined2 <- cbind(feature_abd, fit_sparseDOSSA2$counts)
  
  
  dfMeta_combined <- data.frame(Sample = rep(c(name_physeq,
                                               "SparseDOSSA"),
                                             each = ncol(feature_abd))%>% 
                                  forcats::fct_inorder())
  rownames(dfMeta_combined) <- colnames(matOTU_combined1)
  dfMeta_combined$sample_name <- rownames(dfMeta_combined)
  
  # ordination visualization
  dist_all1 <- matOTU_combined1 %>% 
    phyloseq::otu_table(taxa_are_rows = TRUE) %>% 
    phyloseq::transform_sample_counts(function(x) x / sum(x)) %>% 
    phyloseq::distance(method = "bray")
  ordination <- matOTU_combined %>% 
    phyloseq::otu_table(taxa_are_rows = TRUE) %>% 
    phyloseq::ordinate(method = "MDS", distance = dist_all)
  axes.labels <- paste0(c("Axis 1 (", "Axis 2 ("), 
                        round(ordination$values$Relative_eig[1:2] * 100, digits = 1), 
                        "%)")
  tb_plot <- ordination$vectors[, 1:2] %>% 
    as.data.frame() %>% 
    dplyr::bind_cols(dfMeta_combined)
  
  pval <- vegan::adonis(dist_all ~ Sample, data = tb_plot, permutations = 999)
  
  colors <- c("black", "red")
  names(colors) <- c(name_physeq, "SparseDOSSA")
  p_ordinate <- tb_plot %>% 
    ggplot(aes(x = Axis.1, y = Axis.2)) +
    geom_point(aes(color = Sample)) +
    scale_color_manual(values = colors, name = NULL) +
    theme(legend.position = c(0, 1),
          legend.justification = c(0, 1),
          legend.background = element_blank()) +
    coord_fixed() +
    xlab(axes.labels[1]) + ylab(axes.labels[2]) +
    theme(axis.text = element_blank(), axis.ticks = element_blank()) +
    ggtitle(paste0("PERMANOVA p = ", pval$aov.tab$`Pr(>F)`[1]))
  
  # heatmap visualization
  nFeatures_heatmap <- 20
  tb_heatmap <- matOTU_combined %>% 
    apply(2, MMUPHin:::tss) %>% 
    `[`(1:nFeatures_heatmap, ) %>% 
    {log10(. + 1e-5)} %>% 
    t() %>% 
    as.data.frame() %>% 
    tibble::rownames_to_column("sample_name") %>% 
    dplyr::left_join(dfMeta_combined, by = "sample_name") %>% 
    dplyr::arrange(Sample, -Feature1, -Feature2, -Feature3, -Feature4, 
                   -Feature5, -Feature6, -Feature7, -Feature8) %>% 
    dplyr::mutate(sample_name = sample_name %>% forcats::fct_inorder()) %>% 
    tidyr::gather(key = "feature", value = "Abundance", -sample_name, -Sample) %>% 
    dplyr::mutate(feature = factor(feature, levels = paste0("Feature", nFeatures_heatmap:1)))
  tb_separate <- data.frame(x = ncol(feature_abd),
                            y = -0.5,
                            yend = nFeatures_heatmap + 1.5)
  p_heatmap <- tb_heatmap %>% 
    ggplot() +
    geom_tile(data = tb_heatmap, 
              aes(x = sample_name, y = feature,
                  fill = Abundance)) +
    scale_fill_gradient(low = "black", high = "red", name = "log 10 abundance") +
    theme(axis.title = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank(),
          panel.border = element_blank(),
          legend.position = "top", legend.direction = "horizontal") +
    coord_cartesian(clip = 'off') +
    annotate("segment", 
             x = ncol(feature_abd),
             xend = ncol(feature_abd),
             y = 0.5,
             yend = nFeatures_heatmap + 0.5,
             size = 1, linetype = "dashed", color = "white") +
    annotate("text", x = ncol(feature_abd), y = nFeatures_heatmap + 0.5,
             hjust = 1.1, vjust = 1.1, label = name_physeq, size = 5,
             color = "white") +
    annotate("text", x = ncol(feature_abd), y = nFeatures_heatmap + 0.5,
             hjust = -0.1, vjust = 1.1, label = "SparseDOSSA", size = 5,
             color = "white")
  
  # p distributions
  tb_params <- list(feature_abd,
                    fit_sparseDOSSA$counts) %>% 
    purrr::map2_dfr(c(name_physeq, "SparseDOSSA"),
                    function(mat_otu, i_Sample) {
                      tb_features <- mat_otu %>% 
                        apply(2, MMUPHin:::tss) %>% 
                        as.data.frame() %>% 
                        dplyr::mutate(feature = paste0("Feature", 1:dplyr::n())) %>% 
                        tidyr::gather(key = "sample_name", value = "Abundance", 
                                      -feature) %>% 
                        dplyr::group_by(feature) %>% 
                        dplyr::summarise(Prevalence = log(mean(Abundance > 0)) - log(1 - mean(Abundance > 0)),
                                         `Mean abundance` = mean(log(Abundance[Abundance > 0]) - 
                                                                   log(1 - Abundance[Abundance > 0])),
                                         `Variance` = ifelse(sum(Abundance > 0) > 1,
                                                             var(log(Abundance[Abundance > 0]) - 
                                                                   log(1 - Abundance[Abundance > 0])),
                                                             0)) %>% 
                        dplyr::mutate(Sample = i_Sample)
                    }) %>% 
    dplyr::mutate(Sample = Sample %>% forcats::fct_inorder()) %>% 
    tidyr::gather(key = "Parameter",
                  value = "Value",
                  Prevalence, `Mean abundance`, Variance) %>% 
    dplyr::mutate(Parameter = Parameter %>% forcats::fct_inorder())
  p_dist <- tb_params %>% 
    ggplot(aes(x = Value)) +
    geom_density(aes(color = Sample, fill = Sample), alpha = 0.1) +
    scale_color_manual(values = colors, name = NULL) + 
    scale_fill_manual(values = colors, name = NULL) +
    facet_grid(.~Parameter, scales = "free_x") +
    theme(axis.title.x = element_blank(),
          legend.position = c(1, 1),
          legend.justification = c(1, 1),
          legend.background = element_blank())
  
  p_cohort <- cowplot::plot_grid(p_ordinate, p_heatmap, nrow = 1, align = "h", axis = "tb",
                                 rel_widths = c(1, 1.5)) %>% 
    cowplot::plot_grid(p_dist, ncol = 1, rel_heights = c(1.5, 1))
  save(p_cohort, file = paste0(dir_output, "figure_", name_physeq, ".RData"))
}
l_ps <- list()
for(i in 1:3) {
  load(paste0(dir_output, "figure_", dataset_names[i], ".Rdata"))
  l_ps[[i]] <- p_cohort
}
cowplot::plot_grid(plotlist = l_ps, labels = paste0(c("A) ", "B) ", "C) "), dataset_names),
                   nrow = 3,
                   label_fontface = "plain",
                   label_x = 0,
                   label_size = 20,
                   hjust = 0) %>% 
  ggsave(file = "figures/fig_evaluation/fig_evaluation.pdf", .,
         width = 15, height = 30)
```
