---
title: "Compare Likelihoods"
author: "Siyuan Ma"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "../")
library(magrittr)
library(ggplot2)
```

```{r load data, include=FALSE}
load("../data/physeqs/genera.RData")
physeq <- physeq_genera %>% 
  phyloseq::subset_samples(dataset_name == "MucosalIBD") %>% 
  smar::prune_taxaSamples(flist_taxa = genefilter::kOverA(k = 5, A = 1))
mat_X_count <- t(smar::otu_table2(physeq))
colnames(mat_X_count) <- CRTmicrobiome:::simplify_feature(colnames(mat_X_count))
mat_X <- t(apply(mat_X_count, 1, function(x) x / sum(x)))
```

```{r set up simulation grid}
# set.seed(1)
# K_outer <- 10
# K_inner <- 5
# lambdas <- seq(from = 0.02, to = 0.2, by = 0.02)
# samples_outer <- sample.int(n = K_outer, size = nrow(mat_X), replace = TRUE)
# tb_simulation <- tidyr::crossing(k_outer = seq_len(K_outer),
#                                  k_inner = seq_len(K_inner),
#                                  lambdas = lambdas) %>% 
#   dplyr::mutate(samples_outer = list(samples_outer)) %>% 
#   dplyr::group_by(k_outer) %>% 
#   dplyr::mutate(samples_inner = 
#                   list(sample.int(n = K_inner,
#                                    size = sum(samples_outer[[1]] != k_outer[1]),
#                                    replace = TRUE))) %>% 
#   dplyr::group_by(k_outer, k_inner) %>% 
#   dplyr::mutate(samples = 
#                   list(seq_len(nrow(mat_X)) %>% 
#                          extract(samples_outer[[1]] != k_outer[1]) %>% 
#                          extract(samples_inner[[1]] != k_inner[1])))
# save(tb_simulation, file = "../results/compare_likelihood/tb_simulation.RData")
load("../results/compare_likelihood/tb_simulation.RData")
```

# Fit DM distribution and evaluate likelihood

```{r DM}
mat_X_pseudo <- mat_X_count + 0.5
mat_X_pseudo <- t(apply(mat_X_pseudo, 1, function(x) x / sum(x)))
mat_X_pseudo <- mat_X_count + 0.5
mat_X_pseudo <- t(apply(mat_X_pseudo, 1, function(x) x / sum(x)))
doParallel::registerDoParallel(cores = 3)
ll_dm <- foreach::`%dopar%`(
  foreach::foreach(k_outer = seq_len(max(tb_simulation$k_outer)),
                   .combine = c),
  {
    fit_dm <- 
      dirmult::dirmult(data = mat_X_count[tb_simulation$samples_outer[[1]] != 
                                            k_outer, ],
                       trace = FALSE)
    apply(mat_X_count[tb_simulation$samples_outer[[1]] == 
                        k_outer, ],
          1, function(x) {
            post_alpha <- x + 1 + fit_dm$gamma
            lgamma(sum(post_alpha)) - sum(lgamma(post_alpha)) -
              sum(lgamma(fit_dm$gamma)) + sum(lgamma(fit_dm$gamma))
          })
  }
)
doParallel::stopImplicitCluster()
save(ll_dm, file = "../results/compare_likelihood/ll_dm.RData")
```