---
title: "Which correlation measurement?"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---
```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_knit$set(root.dir = normalizePath(".."))
library(magrittr)
library(ggplot2)
```
```{r source functions, include=FALSE}
smar::sourceDir("../ibd_paper/functions/")
smar::set_ggplot()
```
```{r load data}
# metadata
metaphlan_log <- read.delim("data/hmp1-II/hmp1-II_humann2_logs-mtd.pcl",
                            sep = "\t",
                            check.names = FALSE,
                            stringsAsFactors = FALSE)
df_metadata <- metaphlan_log %>% 
  t() %>% 
  as.data.frame(check.names = FALSE, stringsAsFactors = FALSE) %>% 
  set_colnames(unlist(.[1, ])) %>% 
  dplyr::slice(-1)
df_metadata <- df_metadata %>% 
  dplyr::mutate(READS_initial = as.integer(READS_initial),
                READS_pangenomes_aligned = as.integer(READS_pangenomes_aligned),
                READS_pangenomes_aligned_frac = as.numeric(READS_pangenomes_aligned_frac),
                read_depth = READS_initial * 0.05)
# need to set rownames as dplyr discards them
df_metadata <- df_metadata %>% 
  set_rownames(colnames(metaphlan_log)[-1])

# abd matrix
metaphlan <- read.delim("data/hmp1-II/hmp1-II_metaphlan2-mtd-qcd.pcl",
                        sep = "\t",
                        check.names = FALSE,
                        stringsAsFactors = FALSE)
mat_abd <- metaphlan[-(1:8), -1] %>% 
  as.matrix %>% 
  apply(2, as.numeric) %>% 
  set_rownames(metaphlan[-(1:8), 1])

# common samples
samples_common <- intersect(rownames(df_metadata),
                            colnames(mat_abd))
phylo_all <- phyloseq::phyloseq(phyloseq::otu_table(mat_abd[, samples_common], 
                                                    taxa_are_rows = TRUE),
                                phyloseq::sample_data(df_metadata[samples_common, ]))
```

```{r species level features}
phylo_species <- phyloseq::taxa_names(phylo_all) %>% 
  {and(stringr::str_detect(., stringr::fixed("|s__")),
       !stringr::str_detect(., stringr::fixed("|t__")))} %>% 
  phyloseq::prune_taxa(phylo_all)
```


```{r subset to vaginal}
phylo_species_vaginal <- phyloseq::subset_samples(phylo_species,
                                              STSite == "Posterior_fornix")
phylo_species_vaginal <- phylo_species_vaginal %>% 
  phyloseq::subset_samples(read_depth > 2)
phylo_species_vaginal <- phylo_species_vaginal %>% 
  smar::prune_taxaSamples()
```

```{r fit SparseDOSSA}
dir_output <- "results/correlation/"
dir.create(dir_output, recursive = TRUE, showWarnings = FALSE)
n_i <- smar::sample_data2(phylo_species_vaginal)$read_depth
feature_abd <- SparseDOSSA2::create_template_fromMetaphlan(smar::otu_table2(phylo_species_vaginal),
                                                           n_i)
n_i <- apply(feature_abd, 2, sum)

# run sparseDOSSA estimation and simulation
fit_sparseDOSSA <- SparseDOSSA2::SparseDOSSA2(n_sample = ncol(feature_abd),
                                              n_feature = nrow(feature_abd),
                                              template = feature_abd,
                                              same_features = TRUE,
                                              feature_feature_association = TRUE,
                                              read_depth = median(n_i),
                                              seed = 1)
```

```{r visualize results}
mat_p_data <- sapply(fit_sparseDOSSA$template_fits$em,
                     function(x) x$hidden_param$mu_posterior_ij) %>% 
  t() %>% 
  {exp(.) / (1 + exp(.))}
mat_p_data[feature_abd == 0] <- 0
cor_data <- SparseDOSSA2:::cor2(t(mat_p_data), 
                                method = "spearman", random = TRUE, R = 50, seed = 1)
mat_p_simulate <- fit_sparseDOSSA$hidden_params$mats_basis$mat_basis_shuffled
cor_simulate <- SparseDOSSA2:::cor2(t(mat_p_simulate), 
                                method = "spearman", random = TRUE, R = 50, seed = 1)
mat_p_nocop <- fit_sparseDOSSA$hidden_params$mats_basis$mat_basis_original
cor_nocop <- SparseDOSSA2:::cor2(t(mat_p_nocop), 
                                method = "spearman", random = TRUE, R = 50, seed = 1)

#scatter plot
tb_plot <- data.frame(Original = rep(cor_data[lower.tri(cor_data)], 2),
                      SparseDOSSA2 = c(cor_nocop[lower.tri(cor_data)],
                                       cor_simulate[lower.tri(cor_data)]),
                      Model = rep(c("No copula", "With copula"), each = length(cor_data[lower.tri(cor_data)])))
p_scatter <- tb_plot[sample.int(nrow(tb_plot)), ] %>% 
  ggplot(aes(x = Original, y = SparseDOSSA2)) +
  geom_point(aes(color = Model)) +
  scale_color_manual(values = c("No copula" = "black",
                                "With copula" = "red"),
                     name = NULL) +
  coord_fixed() +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  theme(legend.position = c(0, 1),
        legend.justification = c(0, 1),
        legend.background = element_blank()) +
  ggtitle("Feature-feature association comparison in \nHMP1-II Vaginal")
ggsave(paste0(dir_output, "vaginal.pdf"),
       p_scatter,
       width = 6, height = 6)
```

```{r subset to stool phyla}
phylo_phyla_stool <- phyloseq::taxa_names(phylo_all) %>% 
  {and(stringr::str_detect(., stringr::fixed("|p__")),
       !stringr::str_detect(., stringr::fixed("|c__")))} %>% 
  phyloseq::prune_taxa(phylo_all) %>% 
  phyloseq::subset_samples(STSite == "Stool") %>% 
  phyloseq::subset_samples(read_depth > 2) %>% 
  smar::prune_taxaSamples()
```

```{r fit SparseDOSSA in stool phyla}
n_i <- smar::sample_data2(phylo_phyla_stool)$read_depth
feature_abd <- SparseDOSSA2::create_template_fromMetaphlan(smar::otu_table2(phylo_phyla_stool),
                                                           n_i)
n_i <- apply(feature_abd, 2, sum)

# run sparseDOSSA estimation and simulation
fit_sparseDOSSA <- SparseDOSSA2::SparseDOSSA2(n_sample = ncol(feature_abd),
                                              n_feature = nrow(feature_abd),
                                              template = feature_abd,
                                              same_features = TRUE,
                                              feature_feature_association = TRUE,
                                              read_depth = median(n_i),
                                              seed = 1)
```

```{r visualize results stool}
mat_p_data <- sapply(fit_sparseDOSSA$template_fits$em,
                     function(x) x$hidden_param$mu_posterior_ij) %>% 
  t() %>% 
  {exp(.) / (1 + exp(.))}
mat_p_data[feature_abd == 0] <- 0
cor_data <- SparseDOSSA2:::cor2(t(mat_p_data), 
                                method = "spearman", random = TRUE, R = 50, seed = 1)
mat_p_simulate <- fit_sparseDOSSA$hidden_params$mats_basis$mat_basis_shuffled
cor_simulate <- SparseDOSSA2:::cor2(t(mat_p_simulate), 
                                method = "spearman", random = TRUE, R = 50, seed = 1)
mat_p_nocop <- fit_sparseDOSSA$hidden_params$mats_basis$mat_basis_original
cor_nocop <- SparseDOSSA2:::cor2(t(mat_p_nocop), 
                                method = "spearman", random = TRUE, R = 50, seed = 1)

#scatter plot
tb_plot <- data.frame(Original = rep(cor_data[lower.tri(cor_data)], 2),
                      SparseDOSSA2 = c(cor_nocop[lower.tri(cor_data)],
                                       cor_simulate[lower.tri(cor_data)]),
                      Model = rep(c("No copula", "With copula"), each = length(cor_data[lower.tri(cor_data)])))
p_scatter <- tb_plot[sample.int(nrow(tb_plot)), ] %>% 
  ggplot(aes(x = Original, y = SparseDOSSA2)) +
  geom_point(aes(color = Model)) +
  scale_color_manual(values = c("No copula" = "black",
                                "With copula" = "red"),
                     name = NULL) +
  coord_fixed() +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  theme(legend.position = c(0, 1),
        legend.justification = c(0, 1),
        legend.background = element_blank()) +
  ggtitle("Feature-feature association comparison in \nHMP1-II Stool Phyla")
ggsave(paste0(dir_output, "stool.pdf"),
       p_scatter,
       width = 6, height = 6)
```

```{r study individual vaginal features}
dir_output <- "results/correlation/vag/"
dir.create(dir_output, recursive = TRUE, showWarnings = FALSE)
# n_i <- sample_data2(phylo_species_vag)$read_depth
# doParallel::registerDoParallel(cores = 6)
# l_results <- foreach::`%dopar%`(
#   foreach::foreach(i_feature = phyloseq::taxa_names(phylo_species_vag)), 
#   {
#     y_i <- round(otu_table2(phylo_species_vag)[i_feature, ] * n_i)
#     i_fit <- EM_theta(y_i = y_i, n_i = n_i)
#     return(i_fit)
#   }
# )
# doParallel::stopImplicitCluster()

# plots
mat_otu <- otu_table2(phylo_species_vag)
ind_highVar <- apply(mat_otu, 1, sd)
ind_highVar <- ind_highVar > quantile(ind_highVar, 0.95)

mat_otu <- t(mat_otu[ind_highVar, ])
colnames(mat_otu) <- colnames(mat_otu) %>% 
  stringr::str_replace_all("^.*s\\_\\_", "")

# calculate correlations
methods <- c("kendall", "spearman")
methods_zeros <- c("both", "random", "either", "neither")
ll_cors <- lapply(methods, function(method){
  doParallel::registerDoParallel(cores = 4)
  l_cors <- foreach::`%dopar%`(
    foreach::foreach(method_zeros = methods_zeros),
    {cor2(x = mat_otu, use.zero = method_zeros, method = method, R = 10)}
  )
  doParallel::stopImplicitCluster()
  return(l_cors)
})

ll_p <- ll_cors %>% 
  purrr::map2(methods, 
              function(l_cors, method) {
                l_cors[-2] %>% 
                  purrr::map2(methods_zeros[-2], function(mat_cor, method_zeros) {
                    data.frame(x = l_cors[[2]][lower.tri(mat_cor)],
                               y = mat_cor[lower.tri(mat_cor)]) %>% 
                      ggplot(aes(x = x, y = y)) +
                      geom_point() +
                      geom_abline(intercept = 0, slope = 1, color = "red",
                                  linetype = "dashed") +
                      xlab("random") +
                      ylab(method_zeros) +
                      ggtitle(method) +
                      coord_fixed()
                  })  
              })
l_p <- data.frame(x = ll_cors[[1]][[2]][lower.tri(ll_cors[[1]][[2]])],
                  y = ll_cors[[2]][[2]][lower.tri(ll_cors[[2]][[2]])]) %>% 
  ggplot(aes(x = x, y = y)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1, color = "red",
              linetype = "dashed") +
  xlab("random tau") +
  ylab("random spearman") +
  ggtitle("Compare random") +
  coord_fixed()

sample <- mat_otu
p_hist1 <- sample %>% apply(1, sum) %>% 
  data.frame(total_sum = .) %>% 
  ggplot(aes(x = total_sum)) +
  geom_histogram() +
  ggtitle("original sample")
sample_rand <- mat_otu %>% apply(2, sample)
p_hist3 <- sample_rand %>% apply(1, sum) %>% 
  data.frame(total_sum = .) %>% 
  ggplot(aes(x = total_sum)) +
  geom_histogram() +
  ggtitle("random sample")
features_highVar <- sort(apply(sample, 2, sd), decreasing = TRUE)
tb_features <- tibble::tibble(feature = names(features_highVar),
                              sd = features_highVar) %>% 
  dplyr::mutate(feature_simp = ifelse((1:dplyr::n()) <= 5,
                                      feature,
                                      "Others") %>% 
                  forcats::as_factor())
order <- tb_features$feature
ll_ps <- ll_cors %>% 
  purrr::map2(methods, function(l_cors, method) {
    doParallel::registerDoParallel(cores = 4)
    l_p <- foreach::`%dopar%`(
      foreach::foreach(i = 1:length(methods_zeros)),
      {mat_cor <- l_cors[[i]]
      method_zeros <- methods_zeros[i]
      copula_fit <- copula::normalCopula(param = copula::P2p(mat_cor),
                                         dim = ncol(mat_otu),
                                         dispstr = "un")
      sample_rank <- copula::rCopula(copula_fit, n = nrow(mat_otu))
      sample_rank <- sample_rank %>% 
        apply(2, rank)
      sample_cop <- sapply(1:ncol(sample), 
                           function(j) sort(sample[, j])[sample_rank[, j]])
      colnames(sample_cop) <- colnames(sample)
      mat_cor_sample <- cor2(sample_cop, use.zero = method_zeros,
                             method = method, R = 10)
      mat_cor_rand <- cor2(sample_rand, use.zero = method_zeros,
                             method = method, R = 10)
      dimnames(mat_cor_sample) <- 
        dimnames(mat_cor_rand) <- 
        dimnames(mat_cor) <- 
        list(colnames(sample), colnames(sample))
      p_scatter <- data.frame(x = mat_cor[lower.tri(mat_cor)],
                              y = mat_cor_sample[lower.tri(mat_cor)]) %>% 
        ggplot(aes(x = x, y = y)) +
        geom_point() +
        xlab("original cor") +
        ylab("sample cor") +
        geom_abline(intercept = 0, slope = 1, color = "red",
                    linetype = "dashed") +
        ggtitle(paste0(method, ", ", method_zeros)) +
        coord_fixed()
      p_hist2 <- sample_cop %>% apply(1, sum) %>% 
        data.frame(total_sum = .) %>% 
        ggplot(aes(x = total_sum)) +
        geom_histogram() +
        ggtitle("copula sample")
      
      cowplot::plot_grid(p_scatter, p_hist1, p_hist2, p_hist3,
                         nrow = 1) %>% 
        ggsave(paste0(dir_output, "fig_", method, 
                      "_", method_zeros, ".pdf"),
               ., 
               width = 16, height = 4)
      
      # plot correlations and abundance
      tb_cor <- mat_cor[order, order] %>% 
        as.data.frame() %>% 
        tibble::rownames_to_column("Feature1") %>% 
        dplyr::mutate(Feature1 = factor(Feature1, levels = Feature1)) %>% 
        tidyr::gather(key = Feature2,
                      value = Correlation,
                      -Feature1) %>% 
        dplyr::mutate(Feature2 = factor(Feature2, levels = levels(Feature1))) 
      tb_cor_sample <- mat_cor_sample[order, order] %>% 
        as.data.frame() %>% 
        tibble::rownames_to_column("Feature1") %>% 
        dplyr::mutate(Feature1 = factor(Feature1, levels = Feature1)) %>% 
        tidyr::gather(key = Feature2,
                      value = Correlation,
                      -Feature1) %>% 
        dplyr::mutate(Feature2 = factor(Feature2, levels = levels(Feature1)))
       tb_cor_rand <- mat_cor_rand[order, order] %>% 
        as.data.frame() %>% 
        tibble::rownames_to_column("Feature1") %>% 
        dplyr::mutate(Feature1 = factor(Feature1, levels = Feature1)) %>% 
        tidyr::gather(key = Feature2,
                      value = Correlation,
                      -Feature1) %>% 
        dplyr::mutate(Feature2 = factor(Feature2, levels = levels(Feature1)))
      
      p_heat1 <- tb_cor %>% 
        ggplot(aes(x = Feature1, y = Feature2, fill = Correlation)) +
        geom_tile() +
        theme(
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.title = element_blank(),
          axis.text = element_text(size = 8),
          axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
        scale_fill_gradient2(low = "green", high = "red", mid = "black", midpoint = 0, 
                             limits = c(-1, 1))
      p_heat2 <- tb_cor_sample %>% 
        ggplot(aes(x = Feature1, y = Feature2, fill = Correlation)) +
        geom_tile() +
        theme(
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.title = element_blank(),
          axis.text = element_text(size = 8),
          axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
        scale_fill_gradient2(low = "green", high = "red", mid = "black", midpoint = 0, 
                             limits = c(-1, 1))
      p_heat3 <- tb_cor_rand %>% 
        ggplot(aes(x = Feature1, y = Feature2, fill = Correlation)) +
        geom_tile() +
        theme(
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          axis.title = element_blank(),
          axis.text = element_text(size = 8),
          axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
        scale_fill_gradient2(low = "green", high = "red", mid = "black", midpoint = 0, 
                             limits = c(-1, 1))
      
      p_sample1 <- sample %>% 
        as.data.frame() %>% 
        tibble::rownames_to_column("sample") %>% 
        tidyr::gather(key = feature, value = abundance, -sample) %>% 
        dplyr::left_join(tb_features, by = "feature") %>% 
        dplyr::group_by(sample, feature_simp) %>% 
        dplyr::summarise(abundance = sum(abundance)) %>% 
        dplyr::arrange(feature_simp) %>% 
        dplyr::group_by(sample) %>% 
        dplyr::mutate(abundance1 = abundance[1],
                      abundance2 = abundance[2],
                      abundance3 = abundance[3],
                      abundance4 = abundance[4]) %>% 
        dplyr::ungroup() %>% 
        dplyr::arrange(-abundance1, -abundance2, -abundance3, -abundance4) %>% 
        dplyr::mutate(sample = sample %>% forcats::as_factor()) %>% 
        dplyr::mutate(feature_simp = factor(feature_simp,
                                            levels = rev(levels(feature_simp)))) %>% 
        ggplot(aes(x = sample, y = abundance, fill = feature_simp)) +
        geom_bar(stat = "identity") +
        theme(axis.text.x = element_blank())
      p_sample2 <- sample_cop %>% 
        as.data.frame() %>% 
        tibble::rownames_to_column("sample") %>% 
        tidyr::gather(key = feature, value = abundance, -sample) %>% 
        dplyr::left_join(tb_features, by = "feature") %>% 
        dplyr::group_by(sample, feature_simp) %>% 
        dplyr::summarise(abundance = sum(abundance)) %>% 
        dplyr::arrange(feature_simp) %>% 
        dplyr::group_by(sample) %>% 
        dplyr::mutate(abundance1 = abundance[1],
                      abundance2 = abundance[2],
                      abundance3 = abundance[3],
                      abundance4 = abundance[4]) %>% 
        dplyr::ungroup() %>% 
        dplyr::arrange(-abundance1, -abundance2, -abundance3, -abundance4) %>% 
        dplyr::mutate(sample = sample %>% forcats::as_factor()) %>% 
        dplyr::mutate(feature_simp = factor(feature_simp,
                                            levels = rev(levels(feature_simp)))) %>% 
        ggplot(aes(x = sample, y = abundance, fill = feature_simp)) +
        geom_bar(stat = "identity") +
        theme(axis.text.x = element_blank())
      p_sample3 <- sample_rand %>% 
        as.data.frame() %>% 
        tibble::rownames_to_column("sample") %>% 
        tidyr::gather(key = feature, value = abundance, -sample) %>% 
        dplyr::left_join(tb_features, by = "feature") %>% 
        dplyr::group_by(sample, feature_simp) %>% 
        dplyr::summarise(abundance = sum(abundance)) %>% 
        dplyr::arrange(feature_simp) %>% 
        dplyr::group_by(sample) %>% 
        dplyr::mutate(abundance1 = abundance[1],
                      abundance2 = abundance[2],
                      abundance3 = abundance[3],
                      abundance4 = abundance[4]) %>% 
        dplyr::ungroup() %>% 
        dplyr::arrange(-abundance1, -abundance2, -abundance3, -abundance4) %>% 
        dplyr::mutate(sample = sample %>% forcats::as_factor()) %>% 
        dplyr::mutate(feature_simp = factor(feature_simp,
                                            levels = rev(levels(feature_simp)))) %>% 
        ggplot(aes(x = sample, y = abundance, fill = feature_simp)) +
        geom_bar(stat = "identity") +
        theme(axis.text.x = element_blank())
      cowplot::plot_grid(p_heat1, p_heat2, p_heat3,
                         p_sample1, p_sample2, p_sample3,
                         align = "h", nrow = 2) %>% 
        ggsave(paste0(dir_output, "fig_samples_",
                      method, "_", method_zeros, ".pdf"),
               .,
               width = 30, height = 30)
      
      return(list(p_scatter, p_hist2))
      }
    )
    doParallel::stopImplicitCluster()
    return(l_p)
  })
```

