---
title: "New model for X"
author: "Siyuan Ma"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "../")
library(magrittr)
library(ggplot2)
```

```{r load data, include=FALSE}
load("../data/physeqs/genera.RData")
physeq <- physeq_genera %>% 
  phyloseq::subset_samples(dataset_name == "MucosalIBD") %>% 
  smar::prune_taxaSamples(flist_taxa = genefilter::kOverA(k = 5, A = 1))
mat_X_count <- t(smar::otu_table2(physeq))
colnames(mat_X_count) <- CRTmicrobiome:::simplify_feature(colnames(mat_X_count))
mat_X <- t(apply(mat_X_count, 1, function(x) x / sum(x)))
```

```{r sample from estimated distributions, include=FALSE}
load("../results/EM_diagnostics/mcmc.RData")
params <- fit_EM_mcmc$ll_params[[20]]
samples_A <- SparseDOSSA2:::rcopulasso(n = 10000,
                                       mean = params$mu,
                                       sd = params$sigma,
                                       pi0 = params$pi0,
                                       sigma = solve(params$Omega))
colnames(samples_A) <- colnames(mat_X)
rownames(samples_A) <- paste0("Sample", seq_len(10000))
samples_X <- t(apply(samples_A, 1, function(x) x / sum(x)))
```

```{r plotting, echo=FALSE}
features_order <- colnames(mat_X)[order(-apply(mat_X, 2, mean))]
matOTU_combined <- rbind(mat_X, samples_X[seq_len(nrow(mat_X)), ]) %>% 
  t()
dfMeta_combined <- 
  tibble::tibble(sample_name = c(rownames(mat_X),
                                 rownames(samples_X)[seq_len(nrow(mat_X))]),
                 Sample = rep(c("Original", "SparseDOSSA"),
                              each = nrow(mat_X)) %>% 
                   forcats::as_factor())
nFeatures_heatmap <- 20
tb_heatmap <- matOTU_combined %>% 
  `[`(features_order[seq_len(20)], ) %>% 
  {log10(. + 1e-5)} %>% 
  t() %>% 
  as.data.frame() %>% 
  tibble::rownames_to_column("sample_name") %>% 
  dplyr::left_join(dfMeta_combined, by = "sample_name") %>% 
  dplyr::arrange(Sample, 
                 -!!sym(features_order[1]), -!!sym(features_order[2]),
                 -!!sym(features_order[3]), -!!sym(features_order[4]),
                 -!!sym(features_order[5]), -!!sym(features_order[6]),
                 -!!sym(features_order[7]), -!!sym(features_order[8])) %>% 
  dplyr::mutate(sample_name = sample_name %>% forcats::fct_inorder()) %>% 
  tidyr::gather(key = "feature", value = "Abundance", -sample_name, -Sample) %>% 
  dplyr::mutate(feature = factor(feature, levels = rev(features_order)))
tb_separate <- data.frame(x = nrow(mat_X),
                          y = -0.5,
                          yend = nFeatures_heatmap + 1.5)
p_heatmap <- tb_heatmap %>% 
  ggplot() +
  geom_tile(data = tb_heatmap, 
            aes(x = sample_name, y = feature,
                fill = Abundance)) +
  scale_fill_gradient(low = "black", high = "red", name = "log 10 abundance") +
  theme(axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.border = element_blank(),
        legend.position = "top", legend.direction = "horizontal") +
  coord_cartesian(clip = 'off') +
  annotate("segment", 
           x = nrow(mat_X),
           xend = nrow(mat_X),
           y = 0.5,
           yend = nFeatures_heatmap + 0.5,
           size = 1, linetype = "dashed", color = "white") +
  annotate("text", x = nrow(mat_X), y = nFeatures_heatmap + 0.5,
           hjust = 1.1, vjust = 1.1, label = "Original", size = 5,
           color = "white") +
  annotate("text", x = nrow(mat_X), y = nFeatures_heatmap + 0.5,
           hjust = -0.1, vjust = 1.1, label = "SparseDOSSA", size = 5,
           color = "white")
```

```{r cors, echo=FALSE}
mat_X_filtered <- mat_X[, params$pi0 < 0.8]
features_topbottom <- c(colnames(mat_X_filtered)[order(-apply(mat_X_filtered, 2, mean))][1:10],
                        rev(colnames(mat_X_filtered)[order(apply(mat_X_filtered, 2, mean))][1:10]))
p_cor_data <- cor(mat_X, method = "spearman")[features_topbottom,
                                            features_topbottom] %>% 
  SparseDOSSA2:::make_cortb() %>% 
  dplyr::mutate(feature1 = factor(feature1, levels = features_topbottom),
                feature2 = factor(feature2, levels = features_topbottom)) %>% 
  ggplot(aes(x = feature2,
             y = feature1,
             fill = cor)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", high = "red", 
                       limits = c(-0.5, 0.5),
                       na.value = "white") +
  smar::rotate_xaxis(90)
cor_abs <- SparseDOSSA2:::Rho(solve(params$Omega))
dimnames(cor_abs) <- list(colnames(mat_X), colnames(mat_X))
p_cor_abs <- cor_abs[features_topbottom,
                                            features_topbottom] %>% 
  SparseDOSSA2:::make_cortb() %>% 
  dplyr::mutate(feature1 = factor(feature1, levels = features_topbottom),
                feature2 = factor(feature2, levels = features_topbottom)) %>% 
  ggplot(aes(x = feature2,
             y = feature1,
             fill = cor)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", high = "red", 
                       limits = c(-0.5, 0.5),
                       na.value = "white") +
  smar::rotate_xaxis(90)
p_cor_samples <- cor(samples_X, method = "spearman")[features_topbottom,
                         features_topbottom] %>% 
  SparseDOSSA2:::make_cortb() %>% 
  dplyr::mutate(feature1 = factor(feature1, levels = features_topbottom),
                feature2 = factor(feature2, levels = features_topbottom)) %>% 
  ggplot(aes(x = feature2,
             y = feature1,
             fill = cor)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", high = "red", 
                       limits = c(-0.5, 0.5),
                       na.value = "white") +
  smar::rotate_xaxis(90)
samples_A_random <- apply(samples_A, 2, sample)
samples_X_random <- t(apply(samples_A_random, 1, function(x) x/sum(x)))
p_cor_samples_null <- cor(samples_X_random, method = "spearman")[features_topbottom,
                         features_topbottom] %>% 
  SparseDOSSA2:::make_cortb() %>% 
  dplyr::mutate(feature1 = factor(feature1, levels = features_topbottom),
                feature2 = factor(feature2, levels = features_topbottom)) %>% 
  ggplot(aes(x = feature2,
             y = feature1,
             fill = cor)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", high = "red", 
                       limits = c(-0.5, 0.5),
                       na.value = "white") +
  smar::rotate_xaxis(90)
```
