---
title: "Fit model on vaginal dataset"
author: "Siyuan Ma"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "../")
library(magrittr)
library(ggplot2)
```

```{r load data, include=FALSE}
load("../data/physeqs/HMP1II_vaginal.RData")
physeq <- physeq_vaginal %>% 
  smar::prune_taxaSamples(flist_taxa = genefilter::kOverA(k = 10, A = 2))
mat_X_count <- t(smar::otu_table2(physeq))
colnames(mat_X_count) <- CRTmicrobiome:::simplify_feature(colnames(mat_X_count))
mat_X <- t(apply(mat_X_count, 1, function(x) x / sum(x)))
```

# Run MCMC based EM

```{r EM_mcmc, echo=FALSE}
time <- Sys.time()
fit_EM_mcmc <- SparseDOSSA2:::EM_diagnose(data = mat_X,
                                          controls = list(ncores = 6,
                                                          lambda = 0.2,
                                                          R = 100000,
                                                          subdivisions = 10000,
                                                          burnin = 0.1,
                                                          maxit = 20,
                                                          method = "mcmc",
                                                          verbose = FALSE))
print(Sys.time() - time)
save(fit_EM_mcmc, file = "../results/EM_diagnostics/vaginal_mcmc.RData")
seq_along(fit_EM_mcmc$ll_easums) %>%
  purrr::map_dfr(function(i_iter) {
    tibble::tibble(
      error = mean(fit_EM_mcmc$ll_easums[[i_iter]][, 2]),
      diff = fit_EM_mcmc$ll_params[[i_iter]]$diff[1],
      i_iter = i_iter
    )
  }) %>%
  tidyr::pivot_longer(cols = c("error", "diff")) %>%
  ggplot(aes(x = i_iter, y = log10(value), color = name)) + geom_point()
```

# Run numerical integration based EM

```{r EM_numint, echo=FALSE}
# time <- Sys.time()
# fit_EM_numint <- SparseDOSSA2:::EM_diagnose(data = mat_X,
#                                           controls = list(ncores = 6,
#                                                           lambda = 0.2,
#                                                           R = 10000,
#                                                           subdivisions = 100000,
#                                                           burnin = 0.1,
#                                                           maxit = 20,
#                                                           method = "numint",
#                                                           verbose = FALSE))
# print(Sys.time() - time)
# save(fit_EM_numint, file = "../results/EM_diagnostics/numint.RData")
# seq_along(fit_EM_numint$ll_easums) %>%
#   purrr::map_dfr(function(i_iter) {
#     tibble::tibble(
#       error = mean(fit_EM_numint$ll_easums[[i_iter]][, 2]),
#       diff = fit_EM_numint$ll_params[[i_iter]]$diff[1],
#       i_iter = i_iter
#     )
#   }) %>%
#   tidyr::pivot_longer(cols = c("error", "diff")) %>%
#   ggplot(aes(x = i_iter, y = log10(value), color = name)) + geom_point()
```