---
title: "Format HMP1-II data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
load("data/physeqs/HMP1II_vaginal.RData")
load("data/physeqs/HMP1II_stool.RData")

x_samples_vaginal <- physeq_vaginal %>% 
  smar::otu_table2() %>% 
  t()
# first subset to top 100 samples with deepest sequencing depth
x_samples_vaginal <- 
  x_samples_vaginal[x_samples_vaginal %>% 
                      apply(1, sum) %>% 
                      {order(-.)[1:100]}, ]
# remove features with at most one non-zero values
x_samples_vaginal <- 
  x_samples_vaginal[, (x_samples_vaginal > 0) %>% 
                      apply(2, sum) %>% 
                      {. >= 2}]
# finally subset to top 200 features with largest average relative abundance
x_samples_vaginal <- 
  x_samples_vaginal[, x_samples_vaginal %>% 
                      apply(1, TSS) %>% 
                      apply(1, mean) %>% 
                      {order(-.)[1:200]}]
# set to relative abundance
x_samples_vaginal <- 
  x_samples_vaginal %>% 
  apply(1, TSS) %>% 
  t()

x_samples_stool <- physeq_stool %>% 
  smar::otu_table2() %>% 
  t()
# first subset to top 20 samples with deepest sequencing depth
x_samples_stool <- 
  x_samples_stool[x_samples_stool %>% 
                      apply(1, sum) %>% 
                      {order(-.)[1:10]}, ]
# remove features with at most one non-zero values
x_samples_stool <- 
  x_samples_stool[, (x_samples_stool > 0) %>% 
                      apply(2, sum) %>% 
                      {. >= 2}]
# finally subset to top 10 features with largest average relative abundance
x_samples_stool <- 
  x_samples_stool[, x_samples_stool %>% 
                      apply(1, TSS) %>% 
                      apply(1, mean) %>% 
                      {order(-.)[1:5]}]
stool <- t(x_samples_stool)
save(stool, file = paste0("data/HMP_stool.RData"))
# set to relative abundance
x_samples_stool <- 
  x_samples_stool %>% 
  apply(1, TSS) %>% 
  t()
```