---
title: "Evaluation of SparseDOSSA2 Likelihoods"
author: "Siyuan Ma"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "../")
library(magrittr)
library(ggplot2)
```

```{r load data, include=FALSE}
load("../data/physeqs/genera.RData")
physeq <- physeq_genera %>% 
  phyloseq::subset_samples(dataset_name == "MucosalIBD") %>% 
  smar::prune_taxaSamples(flist_taxa = genefilter::kOverA(k = 5, A = 1))
mat_X_count <- t(smar::otu_table2(physeq))
colnames(mat_X_count) <- CRTmicrobiome:::simplify_feature(colnames(mat_X_count))
mat_X <- t(apply(mat_X_count, 1, function(x) x / sum(x)))
```

```{r set up simulation grid}
dir.create("../results/compare_likelihood/", recursive = TRUE,
           showWarnings = FALSE)
# set.seed(1)
# K_outer <- 10
# K_inner <- 5
# lambdas <- seq(from = 0.02, to = 0.2, by = 0.02)
# samples_outer <- sample.int(n = K_outer, size = nrow(mat_X), replace = TRUE)
# tb_simulation <- tidyr::crossing(k_outer = seq_len(K_outer),
#                                  k_inner = seq_len(K_inner),
#                                  lambdas = lambdas) %>% 
#   dplyr::mutate(samples_outer = list(samples_outer)) %>% 
#   dplyr::group_by(k_outer) %>% 
#   dplyr::mutate(samples_inner = 
#                   list(sample.int(n = K_inner,
#                                    size = sum(samples_outer[[1]] != k_outer[1]),
#                                    replace = TRUE))) %>% 
#   dplyr::group_by(k_outer, k_inner) %>% 
#   dplyr::mutate(samples = 
#                   list(seq_len(nrow(mat_X)) %>% 
#                          extract(samples_outer[[1]] != k_outer[1]) %>% 
#                          extract(samples_inner[[1]] != k_inner[1])))
# save(tb_simulation, file = "../results/compare_likelihood/tb_simulation.RData")
load("../results/compare_likelihood/tb_simulation.RData")
```

# Run numerical integration based EM

```{r EM_numint, echo=FALSE}
# time <- Sys.time()
# fit_EM <- 
#   SparseDOSSA2:::EM_diagnose(
#     data = mat_X[tb_simulation$samples[[i]], ],
#     control = list(ncores = 45,
#                    maxit = 30,
#                    method = "numint",
#                    verbose = FALSE,
#                    control_numint = list(limit_min = 1e-14,
#                                          rel.tol = 1e-4,
#                                          abs.tol = 1e-8,
#                                          subdivisions = 1000)))
# print(Sys.time() - time)
# save(fit_EM, file = 
#        paste0("../results/compare_likelihood/SparseDOSSA2_",
#               i, ".RData"))
# plot(1:30, fit_EM$ll_params %>% purrr::map_dbl("l"))
# plot(1:30, fit_EM$ll_params %>% purrr::map_dbl(~.x$diff[1]))
```

```{r evaluate likelihood}
load(paste0("../results/compare_likelihood/SparseDOSSA2_",
              i, ".RData"))
fit_param <- fit_EM$ll_params[[length(fit_EM$ll_params)]]
doParallel::registerDoParallel(cores = 22)
ll <- foreach::`%dopar%`(
  foreach::foreach(
    i_sample = seq_len(sum(tb_simulation$samples_inner[[i]] == 
                             tb_simulation$k_inner[i])),
    .combine = c),
  {
    x <- mat_X %>% 
      `[`(tb_simulation$samples_outer[[i]] != tb_simulation$k_outer[i], ) %>% 
      `[`(tb_simulation$samples_inner[[i]] == tb_simulation$k_inner[i], ) %>% 
      `[`(i_sample, )
    
    try(SparseDOSSA2:::log_dx(x = x, 
                              pi0 = fit_param$pi0, mu = fit_param$mu,
                              sigma = fit_param$sigma, Omega = fit_param$Omega,
                              offset_a = 1,
                              control = list(jacobian = TRUE)))
  })
doParallel::stopImplicitCluster()
save(ll, file = paste0("../results/compare_likelihood/ll_SparseDOSSA2_",
                       i, ".RData"))
```