---
title: "Simulation subset"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/n/janson_lab/lab/sma/sparsedossa_update/")
library(magrittr)
library(ggplot2)
```

```{r setup2, include=FALSE}
# Registry
# batchtools::makeRegistry(file.dir = "r_batchtools_reg/Simulation_smaller2", package = "magrittr")
batchtools::loadRegistry(file.dir = "r_batchtools_reg/Simulation_smaller2", writeable = TRUE)
batchtools::clearRegistry()

# Grid parameters
ncpus <- 45
partition <- "janson_cascade"
walltime <- 200 * 3600

# Output dir
dir_output <- "/n/janson_lab/lab/sma/sparsedossa_update/results/Simulation_smaller2/"
dir.create(dir_output, recursive = TRUE, showWarnings = FALSE)
smar::sourceDir("SparseDOSSA2/R/")
```

```{r setup simulation params}
# dir_data <- "results/tmp/Stool_vaginal/2020_03_10/"
# load(paste0(dir_data, "tb_job.RData"))
# tb_job <- tb_job %>%
#   dplyr::filter(glasso_method == "huge") %>%
#   dplyr::group_by(i_job) %>%
#   dplyr::mutate(fit_EM =
#                   if(paste0("fit_", i_job, ".RData") %in% list.files(dir_data)) {
#                     load(paste0(dir_data, "fit_", i_job, ".RData"))
#                     list(fit_EM)
#                   } else {
#                     list(NULL)
#                   }) %>%
#   dplyr::ungroup()
# tb_job <- tb_job %>%
#   dplyr::filter(
#     fit_EM %>%
#       purrr::map_lgl(is.null) %>%
#       {!.}
#   ) %>%
#   dplyr::mutate(sparsity = fit_EM %>%
#                   purrr::map_dbl(~.x$l_fits_full[[1]]$fit$Omega %>%
#                                    lower_tri() %>%
#                                    {mean(. == 0)}))
# tb_params <- tb_job %>%
#   dplyr::filter(sparsity > 0.1 & sparsity < 0.9) %>%
#   dplyr::mutate(params = fit_EM %>%
#                   purrr::map(~ .x$l_fits_full[[1]]$fit)) %>%
#   dplyr::select(params, dataset, lambda, sparsity) %>%
#   dplyr::mutate(i_params = seq_len(dplyr::n()))
# # filter parameters so easier to get at least two observations per feature
# tb_params <- tb_params %>%
#   dplyr::mutate(params_sim = params %>%
#                   purrr::map(filter_params))
```

```{r simulate datasets}
# set.seed(1)
# tb_sim <- tb_params %>%
#   tidyr::expand_grid(n = c(100, 200, 400),
#                      R = 1:5) %>%
#   dplyr::mutate(i_sim = seq_len(dplyr::n())) %>%
#   dplyr::group_by(i_sim) %>%
#   dplyr::mutate(a_samples =
#                   simulate_a(n = n, params = params_sim[[1]]) %>%
#                   list(),
#                 x_samples =
#                   t(apply(a_samples[[1]], 1, function(x) x / sum(x))) %>%
#                   list()
#   ) %>%
#   dplyr::ungroup()
```
```{r job grid}
# tb_job <-
#   tibble::tibble(
#     penalize_method = c("huge", "ridge1"),
#     lambdas = list(10^seq(from = -2, to = 0, length.out = 11),
#                    10^seq(from = -5, to = 0, length.out = 6))
#   ) %>%
#   tidyr::expand_grid(tb_sim) %>%
#   dplyr::mutate(i_job = seq_len(dplyr::n()))
# save(tb_job, file = paste0(dir_output, "tb_job.RData"))
load(paste0(dir_output, "tb_job.RData"))
```

```{r one job}
one_job <- function(i_job) {
  future::plan(list(future::sequential, future::multicore))
  i_tb_job <- tb_job[i_job, ]
  x_samples <- i_tb_job$x_samples[[1]]
  
  fit_EM <- EM_diagnose(
    data = x_samples,
    lambdas = i_tb_job$lambdas[[1]],
    control = list(
      abs_tol = 5e-3,
      rel_tol = 1,
      maxit = 30,
      verbose = TRUE,
      debug_dir = paste0(dir_output, i_job, "/")))
  save(fit_EM, file = paste0(dir_output, "fit_", i_job, ".RData"))
}
```

```{r submit jobs}
time_start <- Sys.time()
tb_ids <- batchtools::batchMap(one_job, 
                               i_job = tb_job %>% 
                                 dplyr::filter(n == 100, R == 1) %>% 
                                 extract2("i_job"))
batchtools::batchExport(mget(ls()))
batchtools::submitJobs(
  resources =  list(ncpus = ncpus, 
                    partition = partition, 
                    walltime = walltime))
print(Sys.time() - time_start)
```