---
title: "Summarize results of real-world dataset fitting"
author: "Siyuan Ma"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/n/janson_lab/lab/sma/sparsedossa_update/")
library(magrittr)
library(ggplot2)
dir_output <- "/n/janson_lab/lab/sma/sparsedossa_update/results/Simulation_smaller/"
```

```{r load results, include=FALSE}
# batchtools::loadRegistry(file.dir = "r_batchtools_reg/Simulation_smaller/", writeable = FALSE)
smar::sourceDir("SparseDOSSA2/R/")
# set.seed(1)
# tb_job_params_x <- tb_job %>%
#   dplyr::filter(!duplicated(i_params))
# for(i_params in tb_job_params_x$i_params) {
#   params_sim_x <- params_a_to_x(tb_job_params_x$params_sim[[i_params]])
#   save(params_sim_x, file = paste0(dir_output,
#                                    "params_sim_x_",
#                                    i_params,
#                                    ".RData"))
# }
# tb_job_params_x <- tb_job_params_x %>%
#   dplyr::mutate(params_sim_x =
#                   i_params %>%
#                   purrr::map(
#                     ~{
#                       load(paste0(dir_output,
#                                   "params_sim_x_",
#                                   .x,
#                                   ".RData"))
#                       params_sim_x
#                     })) %>%
#   dplyr::select(i_params, params_sim_x) %>%
#   dplyr::right_join(tb_job, by = "i_params") %>%
#   dplyr::rename(lambda_sim = lambda)
# save(tb_job_params_x, file = paste0(dir_output, "tb_job_params_x.RData"))
# load(paste0(dir_output, "tb_job_params_x.RData"))
# tb_result <- tb_job_params_x %>%
#   dplyr::filter(i_job %in% batchtools::findDone()$job.id) %>%
#   dplyr::group_by(i_job) %>% 
#   dplyr::mutate(fit_EM = {
#     load(paste0(dir_output, "fit_", i_job, ".RData"))
#     list(fit_EM)
#   }) %>% 
#   dplyr::ungroup()
```

```{r format results, include=FALSE}
# tb_result_formatted <- tb_result$i_job %>% 
#   purrr::map_dfr(function(i_job) {
#     tibble::tibble(
#       lambda_fit = tb_result$lambdas[[i_job]],
#       fit = tb_result$fit_EM[[i_job]]$l_fits_full,
#       params_fit = fit %>% 
#         purrr::map("fit"),
#       logLik = params_fit %>% 
#         purrr::map_dbl("logLik"),
#       logLik_CV = tb_result$fit_EM[[i_job]]$logLik_CV %>% 
#         apply(2, function(x){mean(x[x > -Inf])}),
#       sparsity_fit = params_fit %>% 
#         purrr::map_dbl(~.x$Omega %>% lower_tri() %>% {mean(. == 0)}),
#       i_job = i_job
#     )
#   }) %>% 
#   dplyr::select(-fit) %>% 
#   dplyr::filter(!is.na(logLik)) %>% 
#   dplyr::left_join(tb_result, by = "i_job") %>% 
#   dplyr::select(-fit_EM)
# save(tb_result_formatted, file = paste0(dir_output, "tb_result_formatted.RData"))
load(paste0(dir_output, "tb_result_formatted.RData"))
```

Main conclusion: 

* Graphical lasso lands at solutions with different sparsities than the truth as $n \rightarrow \infty$. The solution still induces good $x$ parameter estimations (i.e. non identifiability of the likelihood)?
* Ridge behaves very differently from the real data fit - different sparsity pattern?

# Examine fitted results

```{r examine log likelihood and sparsity, echo=FALSE}
tb_result_formatted %>%
  dplyr::filter(dataset == "vaginal") %>% 
  dplyr::mutate(logLik_CV = ifelse(logLik_CV > -50,
                                   logLik_CV,
                                   NA_real_)) %>% 
  ggplot(aes(x = log10(lambda_fit), y = logLik_CV, color = as.character(R))) +
  geom_point(aes(shape = as.character(n))) +
  geom_line() +
  facet_wrap(~ i_params + penalize_method + n, ncol = 6, scales = "free_x") +
  ggtitle("vaginal sets")

tb_result_formatted %>%
  dplyr::filter(dataset == "vaginal") %>% 
  ggplot(aes(x = log10(lambda_fit), y = sparsity_fit, color = as.character(R))) +
  geom_point(aes(shape = as.character(n))) +
  geom_hline(aes(yintercept = sparsity)) +
  geom_line() +
  facet_wrap(~ i_params + penalize_method + n, ncol = 6, scales = "free_x") +
  ggtitle("vaginal sets")

tb_result_formatted %>%
  dplyr::filter(dataset == "stool") %>% 
  dplyr::mutate(logLik_CV = ifelse(logLik_CV > -250,
                                   logLik_CV,
                                   NA_real_)) %>% 
  ggplot(aes(x = log10(lambda_fit), y = logLik_CV, color = as.character(R))) +
  geom_point(aes(shape = as.character(n))) +
  geom_line() +
  facet_wrap(~ i_params + penalize_method + n, ncol = 6, scales = "free_x") +
  ggtitle("stool sets")

tb_result_formatted %>%
  dplyr::filter(dataset == "stool") %>% 
  ggplot(aes(x = log10(lambda_fit), y = sparsity_fit, color = as.character(R))) +
  geom_point(aes(shape = as.character(n))) +
  geom_hline(aes(yintercept = sparsity)) +
  geom_line() +
  facet_wrap(~ i_params + penalize_method + n, ncol = 6, scales = "free_x") +
  ggtitle("stool sets")

```

## Parameter visualization
```{r examine values, echo=FALSE, fig.width=25, fig.height=10}
tb_result_top_CV <- tb_result_formatted %>%
  dplyr::group_by(i_job) %>%
  dplyr::arrange(-logLik_CV) %>%
  dplyr::slice(1) %>%
  dplyr::ungroup()
# set.seed(1)
# for(i in seq_len(nrow(tb_result_top_CV))) {
#   print(i)
#   load(paste0(dir_output, "fit_", tb_result_top_CV$i_job[i], ".RData"))
#   params_fit_x <- params_a_to_x(fit_EM$l_fits_full[[tb_result_top_CV$i_lambda[i]]]$fit)
#   save(params_fit_x, file = paste0(dir_output,
#                                    "params_fit_x_",
#                                    tb_result_top_CV$i_job[i],
#                                    ".RData"))
# }
tb_result_top_CV <- tb_result_top_CV %>% 
  dplyr::group_by(i_job) %>% 
  dplyr::mutate(params_fit_x = {
    load(paste0(dir_output,
                "params_fit_x_", i_job, ".RData"))
    list(params_fit_x)
  }) %>% 
  dplyr::ungroup()

for(i_dataset in c("vaginal", "stool")) {
  p <- seq_len(nrow(tb_result_top_CV)) %>%
    purrr::map_dfr(function(i_row) {
      tibble::tibble(i_job = tb_result_top_CV$i_job[i_row],
                     x_param = tb_result_top_CV$params_sim_x[[i_row]]$pi0,
                     x_fit_param = tb_result_top_CV$params_fit_x[[i_row]]$pi0)
    }) %>%
    dplyr::left_join(tb_result_top_CV, by = "i_job") %>%
    dplyr::filter(dataset == i_dataset) %>%
    ggplot(aes(x = x_param, y = x_fit_param, color = as.character(R))) +
    geom_point() +
    geom_abline(intercept = 0, slope = 1) +
    ggpubr::stat_cor() +
    facet_wrap(~ i_params + penalize_method + n, ncol = 6) +
    coord_fixed() +
    ggtitle(paste0(i_dataset, " x_pi0"))
  print(p)
  
  p <- seq_len(nrow(tb_result_top_CV)) %>%
    purrr::map_dfr(function(i_row) {
      tibble::tibble(i_job = tb_result_top_CV$i_job[i_row],
                     x_param = tb_result_top_CV$params_sim_x[[i_row]]$mu,
                     x_fit_param = tb_result_top_CV$params_fit_x[[i_row]]$mu)
    }) %>%
    dplyr::left_join(tb_result_top_CV, by = "i_job") %>%
    dplyr::filter(dataset == i_dataset) %>%
    ggplot(aes(x = x_param, y = x_fit_param, color = as.character(R))) +
    geom_point() +
    geom_abline(intercept = 0, slope = 1) +
    ggpubr::stat_cor() +
    facet_wrap(~ i_params + penalize_method + n, ncol = 6) +
    coord_fixed() +
    ggtitle(paste0(i_dataset, " x_mu"))
  print(p)
  
  p <- seq_len(nrow(tb_result_top_CV)) %>%
    purrr::map_dfr(function(i_row) {
      tibble::tibble(i_job = tb_result_top_CV$i_job[i_row],
                     x_param = tb_result_top_CV$params_sim_x[[i_row]]$sigma,
                     x_fit_param = tb_result_top_CV$params_fit_x[[i_row]]$sigma)
    }) %>%
    dplyr::left_join(tb_result_top_CV, by = "i_job") %>%
    dplyr::filter(dataset == i_dataset) %>%
    ggplot(aes(x = x_param, y = x_fit_param, color = as.character(R))) +
    geom_point() +
    geom_abline(intercept = 0, slope = 1) +
    ggpubr::stat_cor() +
    facet_wrap(~ i_params + n, ncol = 3) +
    facet_wrap(~ i_params + penalize_method + n, ncol = 6) +
    coord_fixed() +
    ggtitle(paste0(i_dataset, " x_sigma"))
  print(p)
  # 
  n_feature <- tb_result_top_CV %>% 
    dplyr::filter(dataset == i_dataset) %>% 
    extract2("params_fit_x") %>% 
    {length(.[[1]]$pi0)}
  features_subset <- sample.int((n_feature - 1) * (n_feature - 2) / 2, size = 1000)
  p <- seq_len(nrow(tb_result_top_CV)) %>%
    purrr::map_dfr(function(i_row) {
      tibble::tibble(i_job = tb_result_top_CV$i_job[i_row],
                     x_param = tb_result_top_CV$params_sim_x[[i_row]]$Corr %>% lower_tri() %>% {.[features_subset]},
                     x_fit_param = tb_result_top_CV$params_fit_x[[i_row]]$Corr %>% lower_tri() %>% {.[features_subset]})
    }) %>%
    dplyr::left_join(tb_result_top_CV, by = "i_job") %>%
    dplyr::filter(dataset == i_dataset) %>%
    ggplot(aes(x = x_param, y = x_fit_param, color = as.character(R))) +
    geom_point() +
    geom_abline(intercept = 0, slope = 1) +
    ggpubr::stat_cor() +
    facet_wrap(~ i_params + penalize_method + n, ncol = 6) +
    coord_fixed() +
    ggtitle(paste0(i_dataset, " x_Corr"))
  print(p)
}

# for(i_dataset in c("vaginal", "stool")) {
#   
#   p <- seq_len(nrow(tb_result_top_CV)) %>%
#     purrr::map_dfr(function(i_row) {
#       tibble::tibble(i_job = tb_result_top_CV$i_job[i_row],
#                      a_param = tb_result_top_CV$params_sim[[i_row]]$mu,
#                      a_fit_param = tb_result_top_CV$params_fit[[i_row]]$mu)
#     }) %>%
#     dplyr::left_join(tb_result_top_CV, by = "i_job") %>%
#     dplyr::filter(dataset == i_dataset) %>%
#     ggplot(aes(x = a_param, y = a_fit_param, color = as.character(R))) +
#     geom_point() +
#     geom_abline(intercept = 0, slope = 1) +
#     ggpubr::stat_cor() +
#     facet_wrap(~ i_params + penalize_method + n, ncol = 6) +
#     coord_fixed() +
#     ggtitle(paste0(i_dataset, " a_mu"))
#   print(p)
#   
#   p <- seq_len(nrow(tb_result_top_CV)) %>%
#     purrr::map_dfr(function(i_row) {
#       tibble::tibble(i_job = tb_result_top_CV$i_job[i_row],
#                      a_param = tb_result_top_CV$params_sim[[i_row]]$sigma,
#                      a_fit_param = tb_result_top_CV$params_fit[[i_row]]$sigma)
#     }) %>%
#     dplyr::left_join(tb_result_top_CV, by = "i_job") %>%
#     dplyr::filter(dataset == i_dataset) %>%
#     ggplot(aes(x = a_param, y = a_fit_param, color = as.character(R))) +
#     geom_point() +
#     geom_abline(intercept = 0, slope = 1) +
#     ggpubr::stat_cor() +
#     facet_wrap(~ i_params + n, ncol = 3) +
#     facet_wrap(~ i_params + penalize_method + n, ncol = 6) +
#     coord_fixed() +
#     ggtitle(paste0(i_dataset, " a_sigma"))
#   print(p)
#   # 
#   n_feature <- tb_result_top_CV %>% 
#     dplyr::filter(dataset == i_dataset) %>% 
#     extract2("params_fit") %>% 
#     {length(.[[1]]$pi0)}
#   features_subset <- sample.int((n_feature - 1) * (n_feature - 2) / 2, size = 1000)
#   p <- seq_len(nrow(tb_result_top_CV)) %>%
#     purrr::map_dfr(function(i_row) {
#       tibble::tibble(i_job = tb_result_top_CV$i_job[i_row],
#                      a_param = tb_result_top_CV$params_sim[[i_row]]$Omega %>% lower_tri() %>% {.[features_subset]},
#                      a_fit_param = tb_result_top_CV$params_fit[[i_row]]$Omega %>% lower_tri() %>% {.[features_subset]})
#     }) %>%
#     dplyr::left_join(tb_result_top_CV, by = "i_job") %>%
#     dplyr::filter(dataset == i_dataset) %>%
#     ggplot(aes(x = a_param, y = a_fit_param, color = as.character(R))) +
#     geom_point() +
#     geom_abline(intercept = 0, slope = 1) +
#     ggpubr::stat_cor() +
#     facet_wrap(~ i_params + penalize_method + n, ncol = 6) +
#     coord_fixed() +
#     ggtitle(paste0(i_dataset, " a_Omega"))
#   print(p)
# }
```