---
title: "Test_fitting"
author: "Siyuan Ma"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
dir_project <- "/n/hutlab11_nobackup/users/syma/sparsedossa_update/"
# dir_project <- "~/Dropbox (Harvard University)/sparsedossa_update/"
knitr::opts_knit$set(root.dir = dir_project)
library(magrittr)
library(ggplot2)
dir_output <- paste0(dir_project, "results/Test_fitting/")
dir.create(dir_output, recursive = TRUE, showWarnings = FALSE)
```

```{r setup cluster parameter}
ncpus <- 45
walltime <- 3600 * 4
```

```{r set up simulation grid}
# tb_simulation <- tidyr::crossing(
#   n = c(100),
#   p = c(3, 5, 10),
#   pi0 = c(0, 0.25, 0.5),
#   mu = c(0),
#   sigma = c(1),
#   Sigma_diag = c(1),
#   Sigma_off_diag = c(0, 0.9, -0.1),
#   n_r = c(1000000),
#   maxit = 1000,
#   R = seq_len(10)
# ) %>%
#   dplyr::mutate(i_sim = 1:(dplyr::n())) %>%
#   dplyr::group_by(i_sim) %>%
#   dplyr::mutate(params = list(pi0 = rep(pi0, p),
#                               mu = rep(mu, p),
#                               sigma = rep(sigma, p),
#                               Sigma = diag(rep(Sigma_diag, p)) -
#                                 diag(rep(Sigma_off_diag, p)) +
#                                 matrix(Sigma_off_diag, p, p)) %>%
#                   list()) %>%
#   dplyr::ungroup()
# set.seed(1)
# l_sets <- seq_len(nrow(tb_simulation)) %>%
#   purrr::map(function(i_sim) {
#     i_tb_simulation <- tb_simulation[i_sim, ]
#     params_truth <- i_tb_simulation$params[[1]]
#     params_truth$Omega <- solve(params_truth$Sigma)
# 
#     a_samples_fit <- SparseDOSSA2:::rcopulasso(n = i_tb_simulation$n,
#                                                pi0 = params_truth$pi0,
#                                                mu = params_truth$mu,
#                                                sigma = params_truth$sigma,
#                                                Omega = params_truth$Omega)
#     return(a_samples_fit)
#   })
# save(l_sets, file = paste0(dir_output, "a_sets.RData"))
# tb_simulation <- tb_simulation %>%
#   dplyr::mutate(a_set = l_sets) %>%
#   tidyr::crossing(lambda = exp(seq(log(1e-3), log(1), length.out = 7))) %>%
#   dplyr::mutate(i_setup = seq_len(dplyr::n()))
# save(tb_simulation, file = paste0(dir_output, "tb_simulation.RData"))
load(paste0(dir_output, "tb_simulation.RData"))
# njobs <- 10
njobs <- nrow(tb_simulation)
```

```{r simulation task}
one_job <- function(i_job) {
  future::plan(future::multicore)
  # set.seed(i_job)
  i_tb_simulation <- tb_simulation[i_job, ]
  params_truth <- i_tb_simulation$params[[1]]
  params_truth$Omega <- solve(params_truth$Sigma)

  # simulate data to fit on
  a_samples_fit <- i_tb_simulation$a_set[[1]]
  a_samples_fit <- a_samples_fit[!apply(a_samples_fit == 0, 1, all), ]
  x_samples_fit <- t(apply(a_samples_fit, 1, function(x) x / sum(x)))

  # fit SparseDOSSA
  time_start <- Sys.time()
  fit_EM <- SparseDOSSA2:::EM_diagnose(
    data = x_samples_fit,
    control = list(lambda = i_tb_simulation$lambda,
                   maxit = i_tb_simulation$maxit,
                   abs_tol = 1e-3,
                   rel_tol = 1e-2,
                   control_numint = list(limit_max = 1400,
                                         limit_min = 1e-14,
                                         method = "hcubature",
                                         abs_tol = 0),
                   verbose = TRUE,
                   debug = paste0(dir_output, "debug_", i_job, ".RData")))
  save(fit_EM, file = paste0(dir_output, "fit_EM_", i_job, ".RData"))
  time <- Sys.time() - time_start
  
  ## Evaluate compositional variable parameters
  a_samples <- SparseDOSSA2:::rcopulasso(n = i_tb_simulation$n_r,
                                         pi0 = params_truth$pi0,
                                         mu = params_truth$mu,
                                         sigma = params_truth$sigma,
                                         Omega = params_truth$Omega)
  a_samples <- a_samples[!apply(a_samples == 0, 1, all), ]
  x_samples <- t(apply(a_samples, 1, function(x) x / sum(x)))
  params_fit <- fit_EM$ll_params[[length(fit_EM$ll_params)]]
  a_samples_SparseDOSSA2 <- SparseDOSSA2:::rcopulasso(n = i_tb_simulation$n_r,
                                                      pi0 = params_fit$pi0,
                                                      mu = params_fit$mu,
                                                      sigma = params_fit$sigma,
                                                      Omega = params_fit$Omega)
  a_samples_SparseDOSSA2 <- a_samples_SparseDOSSA2[!apply(a_samples_SparseDOSSA2 == 0, 1, all), ]
  x_samples_SparseDOSSA2 <- t(apply(a_samples_SparseDOSSA2, 1, function(x) x / sum(x)))
  
  # compile results
  params_x <- list(x_samples, x_samples_SparseDOSSA2) %>%
    purrr::map(~ c(SparseDOSSA2:::get_marginals(.x) %>% as.data.frame(),
                   list(Corr = cor(.x, method = "spear")))) %>%
    set_names(c("truth", "fit"))
  params_a <- list(params_truth, params_fit) %>%
    purrr::map(~.x[c("pi0", "mu", "sigma", "Omega")]) %>%
    set_names(c("truth", "fit"))
  
  result <- list(params_x = params_x,
                 params_a = params_a,
                 time = time)
  save(result, file = paste0(dir_output, "result_", i_job, ".RData"))
  
  return(result)
}
```

```{r submit job}
time_start <- Sys.time()
future.batchtools::batchtools_slurm %>%
  future::plan(resources = list(ncpus = ncpus,
                                walltime = walltime),
               template = "sma")
result_files <- list.files(dir_output, pattern = "^result")
i_results <- result_files %>% 
  gsub("result_", "", ., fixed = TRUE) %>% 
  gsub(".RData", "", ., fixed = TRUE) %>% 
  as.numeric()
l_results <- list()
for(i_job in setdiff(seq_len(njobs), i_results)) {
  l_results[[i_job]] <- future::future(one_job(i_job))
}
save(l_results, file = paste0(dir_output, "l_results.RData"))
```

```{r debug}
debug_files <- list.files(dir_output, pattern = "^debug_")
i_debug <- debug_files %>% 
  gsub("debug_", "", ., fixed = TRUE) %>% 
  gsub(".RData", "", ., fixed = TRUE) %>% 
  as.numeric()
setdiff(i_debug, i_results)

one_debug <- function(i_job) {
  
  load(paste0("/n/hutlab11_nobackup/users/syma/sparsedossa_update/results/Test_fitting/debug_", 
              i_job, ".RData"))
  ll_easums <- res_tmp$ll_easums
  ll_params <- res_tmp$ll_params
  tb_max_diff_easums <- 
    seq_along(ll_easums)[-1] %>% 
    purrr::map_dbl(
      ~ SparseDOSSA2:::get_diff(ll_easums[[.x]][, 1],
                                ll_easums[[.x - 1]][, 1],
                                "rel") %>% 
        max
    ) %>% 
    tibble::tibble(diff = .,
                   i = seq_along(ll_easums)[-1])
  
  tb_max_diff_params <- ll_params %>% 
    purrr::map_dfr(
      ~ tibble::tibble(sigma = .x$diff[3],
                       Sigma = .x$diff[4])
    ) %>% 
    dplyr::mutate(i = seq_along(ll_easums))
  
  p1 <- tb_max_diff_easums %>% 
    ggplot(aes(x = i,
               y = diff)) +
    geom_point() + geom_line() +
    ggtitle(i_job)
  
  p2 <- tb_max_diff_params %>% 
    ggplot(aes(x = i,
               y = sigma)) +
    geom_point() + geom_line()
  
  p3 <- tb_max_diff_params %>% 
    ggplot(aes(x = i,
               y = Sigma)) +
    geom_point() + geom_line()
  
  cowplot::plot_grid(p1, p2, p3,
                     nrow = 1) %>% 
    return()
}

pdf(paste0(dir_output, "debug.pdf"),
    width = 12, height = 4)
for(i_job in setdiff(i_debug, i_results)) {
    print(one_debug(i_job))
}
dev.off()
```