---
title: "Fit on stool and vaginal"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/n/janson_lab/lab/sma/sparsedossa_update/")
library(magrittr)
library(ggplot2)
```

```{r setup2, include=FALSE}
# Registry
# batchtools::makeRegistry(file.dir = "r_batchtools_reg/Test_intLimits/", package = "magrittr")
batchtools::loadRegistry(file.dir = "r_batchtools_reg/Test_intLimits/", writeable = TRUE)
batchtools::clearRegistry()

# Grid parameters
ncpus <- 31
partition <- "janson"
walltime <- 10 * 3600

# Output dir
dir_output <- "/n/janson_lab/lab/sma/sparsedossa_update/results/Test_intLimits/"
dir.create(dir_output, recursive = TRUE, showWarnings = FALSE)
smar::sourceDir("SparseDOSSA2/R/")
```

```{r setup simulation params}
tb_simulation <- tidyr::crossing(
  dataset = c("vaginal", "stool"),
  lambda = 10^seq(from = -1, to = 0, length.out = 21),
  maxit = 1000
)
save(tb_simulation, file = paste0(dir_output, "tb_simulation.RData"))
njobs <- nrow(tb_simulation)
```

```{r load datasets}
load("data/physeqs/HMP1II_vaginal.RData")
load("data/physeqs/HMP1II_stool.RData")
x_samples_vaginal <- physeq_vaginal %>% 
  smar::otu_table2() %>% 
  t()
x_samples_vaginal <- x_samples_vaginal[, apply(x_samples_vaginal > 0, 2, sum) >= 5]
x_samples_vaginal <- apply(x_samples_vaginal, 1, function(x) x / sum(x)) %>% 
  t()

x_samples_stool <- physeq_stool %>% 
  smar::otu_table2() %>% 
  t()
x_samples_stool <- x_samples_stool[, apply(x_samples_stool > 0, 2, sum) >= 5]
x_samples_stool <- apply(x_samples_stool, 1, function(x) x / sum(x)) %>% 
  t()
```

```{r simulation task}
one_job <- function(i_job) {
  future::plan(list(future::sequential, future::multicore))
  i_tb_simulation <- tb_simulation[i_job, ]
  if(i_tb_simulation$dataset == "vaginal")
    x_samples <- x_samples_vaginal
  if(i_tb_simulation$dataset == "stool")
    x_samples <- x_samples_stool

  # fit SparseDOSSA
  time_start <- Sys.time()
  fit_EM <- EM_diagnose(
    data = x_samples,
    lambdas = i_tb_simulation$lambda,
    control = list(maxit = i_tb_simulation$maxit,
                   abs_tol = 1e-3,
                   rel_tol = 1e-2,
                   control_numint = list(limit_max = 1400,
                                         limit_min = 1e-14,
                                         method = "hcubature",
                                         abs_tol = 0),
                   verbose = TRUE,
                   debug_dir = paste0(dir_output, i_job, "/")))
  save(fit_EM, file = paste0(dir_output, "fit_", i_job, ".RData"))
}
```

```{r submit jobs}
time_start <- Sys.time()
tb_ids <- batchtools::batchMap(one_job, 
                               i_job = seq_len(njobs))
batchtools::batchExport(mget(ls()))
batchtools::submitJobs(resources =  list(ncpus = ncpus, partition = partition, walltime = walltime))
print(Sys.time() - time_start)
```