---
title: "Test dx in 2d"
author: "Siyuan Ma"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "../")
library(magrittr)
library(ggplot2)
dir.create("../results/check_likelihood")
```

```{r likelihood functions, include = FALSE}
dx_sigma_2d <- function(sigma1, sigma2,
                        mat_X, 
                        pi0, mu, Omega,
                        offset_a) {
  sum(vapply(seq_len(nrow(mat_X)),
             function(i_sample)
               SparseDOSSA2:::log_dx(x = mat_X[i_sample, ],
                                     pi0 = pi0, 
                                     mu = mu, 
                                     sigma = c(sigma1, sigma2),
                                     Omega = Omega,
                                     offset_a = offset_a[i_sample],
                                     control = list(limit_max = 1000)),
             0.0))
}
```

```{r parameters, include = FALSE}
mat_X <- matrix(c(0.5, 0.5,
                  0.1, 0.9,
                  0.8, 0.2),
                ncol = 2, byrow = TRUE)
pi0 <- c(0, 0)
mu <- c(0, 0)
Omega <- diag(c(1, 1))
df_dx <- 
  tidyr::crossing(sigma1 = exp(seq(log(1e-10), log(10), length.out = 100)),
                  sigma2 = exp(seq(log(1e-10), log(10), length.out = 100)))
```

```{r evaluates}
time <- Sys.time()
doParallel::registerDoParallel(cores = 3)
df_dx$l <- foreach::`%dopar%`(
  foreach::foreach(i = seq_len(nrow(df_dx)),
                   .combine = "c"),
  {
    if(df_dx$sigma1[i] < df_dx$sigma2[i])
      offset_a <- exp(mu[1]) / mat_X[, 1]
    else
      offset_a <- exp(mu[2]) / mat_X[, 2]
    dx_sigma_2d(sigma1 = df_dx$sigma1[i],
                sigma2 = df_dx$sigma2[i],
                mat_X = mat_X,
                pi0 = pi0, mu = mu, Omega = Omega,
                offset_a = offset_a)
  })
doParallel::stopImplicitCluster()
Sys.time() - time
save(df_dx, file = "../results/check_likelihood/df_dx.RData")
```
```{r plotting}
df_plot <- df_dx %>% dplyr::filter(l > -20)
df_plot %>% 
  ggplot(aes(x = log(sigma1), 
             y = log(sigma2),
             fill = l)) +
  geom_tile() +
  scale_fill_gradient2(low = "green", mid = "black", high = "red",
                       midpoint = median(setdiff(df_plot$l, -Inf)),
                       na.value = "white")
df_dx %>% 
  dplyr::filter(sigma2 == 1,
                log(sigma1) > -15) %>% 
  ggplot(aes(x = log(sigma1),
             y = l)) +
  geom_point()
```

