---
title: "Test_fitting"
author: "Siyuan Ma"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---
  
```{r setup, include=FALSE}
# dir_project <- "/n/hutlab11_nobackup/users/syma/sparsedossa_update/"
dir_project <- "~/Dropbox (Harvard University)/sparsedossa_update/"
knitr::opts_knit$set(root.dir = dir_project)
library(magrittr)
library(ggplot2)
dir_output <- paste0(dir_project, "results/Test_fitting/smaller/")
dir.create(dir_output, recursive = TRUE, showWarnings = FALSE)
```

```{r setup cluster parameter}
ncpus <- 45
walltime <- 3600 * 24
```

```{r set up simulation grid}
tb_simulation <- tidyr::crossing(
  p = c(5, 10),
  pi0 = c(0, 0.5),
  mu = c(0),
  sigma = c(1),
  Sigma_diag = c(1),
  Sigma_off_diag = c(0),
  n = c(1000),
  n_r = c(100000),
  lambda = exp(seq(log(1e-2), log(100), length.out = 5)),
  maxit = 100
) %>% 
  dplyr::mutate(i_setup = 1:(dplyr::n())) %>% 
  dplyr::group_by(i_setup) %>% 
  dplyr::mutate(params = list(pi0 = rep(pi0, p),
                              mu = rep(mu, p),
                              sigma = rep(sigma, p),
                              Sigma = diag(rep(Sigma_diag, p)) -
                                diag(rep(Sigma_off_diag, p)) +
                                matrix(Sigma_off_diag, p, p)) %>% 
                  list())
njobs <- nrow(tb_simulation)
```

```{r simulation task}
one_job <- function(i_job) {
  future::plan(future::multicore)
  set.seed(i_job)
  i_tb_simulation <- tb_simulation[i_job, ]
  params_truth <- i_tb_simulation$params[[1]]
  params_truth$Omega <- solve(params_truth$Sigma)

  # simulate data to fit on
  a_samples_fit <- SparseDOSSA2:::rcopulasso(n = i_tb_simulation$n,
                                             pi0 = params_truth$pi0,
                                             mu = params_truth$mu,
                                             sigma = params_truth$sigma,
                                             Omega = params_truth$Omega)
  save(a_samples_fit, file = paste0(dir_output, "a_samples_fit_", i_job, ".RData"))
  a_samples_fit <- a_samples_fit[!apply(a_samples_fit == 0, 1, all), ]
  x_samples_fit <- t(apply(a_samples_fit, 1, function(x) x / sum(x)))

  # fit SparseDOSSA
  fit_EM <- SparseDOSSA2:::EM_diagnose(
    data = x_samples_fit,
    control = list(lambda = i_tb_simulation$lambda,
                   maxit = i_tb_simulation$maxit,
                   abs_tol = 1e-3,
                   verbose = FALSE,
                   control_numint = list(limit_min = 1e-14,
                                         rel.tol = 1e-4,
                                         abs.tol = 1e-8,
                                         subdivisions = 1000)))
  save(fit_EM, file = paste0(dir_output, "fit_EM_", i_job, ".RData"))

  ## Evaluate compositional variable parameters
  a_samples <- SparseDOSSA2:::rcopulasso(n = i_tb_simulation$n_r,
                                         pi0 = params_truth$pi0,
                                         mu = params_truth$mu,
                                         sigma = params_truth$sigma,
                                         Omega = params_truth$Omega)
  a_samples <- a_samples[!apply(a_samples == 0, 1, all), ]
  x_samples <- t(apply(a_samples, 1, function(x) x / sum(x)))
  params_fit <- fit_EM$ll_params[[length(fit_EM$ll_params)]]
  a_samples_SparseDOSSA2 <- SparseDOSSA2:::rcopulasso(n = i_tb_simulation$n_r,
                                                      pi0 = params_fit$pi0,
                                                      mu = params_fit$mu,
                                                      sigma = params_fit$sigma,
                                                      Omega = params_fit$Omega)
  a_samples_SparseDOSSA2 <- a_samples_SparseDOSSA2[!apply(a_samples_SparseDOSSA2 == 0, 1, all), ]
  x_samples_SparseDOSSA2 <- t(apply(a_samples_SparseDOSSA2, 1, function(x) x / sum(x)))
  params_x <- list(x_samples, x_samples_SparseDOSSA2) %>%
    purrr::map(~ c(SparseDOSSA2:::get_marginals(.x) %>% as.data.frame(),
                   list(Corr = cor(.x, method = "spear")))) %>%
    set_names(c("truth", "fit"))
  save(params_x, file = paste0(dir_output, "params_x_", i_job, ".RData"))

  params_a <- list(params_truth, params_fit) %>%
    purrr::map(~.x[c("pi0", "mu", "sigma", "Omega")]) %>%
    set_names(c("truth", "fit"))
  return(list(params_a = params_a,
              params_x = params_x))
}
```

```{r submit job}
future.batchtools::batchtools_slurm %>%
  future::plan(resources = list(ncpus = ncpus,
                                walltime = walltime),
               template = "sma")
l_results <- list()
for(i_job in seq_len(njobs)) {
  l_results[[i_job]] <- future::future(one_job(i_job))
}
for(i_job in seq_len(njobs)) {
  l_results[[i_job]] <- try(future::value(l_results[[i_job]]))
}
save(l_results, file = paste0(dir_output, "l_results.RData"))
```

```{r visaulize}

```
